// flow-typed signature: aafa570ba526163b05a42a105d9ccb85
// flow-typed version: <<STUB>>/@codedungeon/gunner_v0.77.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codedungeon/gunner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codedungeon/gunner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codedungeon/gunner/example' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/example/src/commands/hello' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/core_commands/default' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/core_commands/make-command' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/core_commands/make-extension' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/core_commands/new' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/core_commands/sayHello' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/core_commands/test-prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/log-keypress' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-async' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-autocomplete' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-editable-choices-header' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-invisible' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-multiple' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-number-multiple' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-number' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-option-async' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-quiz' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/prompts/test-snippet' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/security/security' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/security/security.lib' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/security/test-security' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/templates/test-module' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/templates/test' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test_getOptionValue' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-boolean' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-cli' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-confirm' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-directoryList' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-environment' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-everything' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-form' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-fs-promise-async' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-fs-promise' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-get-ip' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-hooks' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-print-class' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test-print' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/sandbox/test' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/default' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/generate-snippet' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/make-command' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/make-extension' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/new' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/quick-prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/sayHello' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/commands/test-prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/extensions/hello-extension' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/extensions/info-extension' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/gunner' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/inspector' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/templates/prettier.config' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/api' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/app-old' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/app' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/arrays' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/config' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/environment' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/filesystem' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/globals' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/helpers' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/multi-prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/packageManager' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/print' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/print2' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/security' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/security.lib' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/strings' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/system' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/table' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/template-eta' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/toolbox/template' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/utils/input' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/utils/prompt' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/src/utils/question' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/tasks/bumpBuild' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/tasks/deploy' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/tasks/lint' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/tasks/test' {
  declare module.exports: any;
}

declare module '@codedungeon/gunner/tasks/todo' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codedungeon/gunner/example/index' {
  declare module.exports: $Exports<'@codedungeon/gunner/example'>;
}
declare module '@codedungeon/gunner/example/index.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/example'>;
}
declare module '@codedungeon/gunner/example/src/commands/hello.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/example/src/commands/hello'>;
}
declare module '@codedungeon/gunner/index' {
  declare module.exports: $Exports<'@codedungeon/gunner'>;
}
declare module '@codedungeon/gunner/index.js' {
  declare module.exports: $Exports<'@codedungeon/gunner'>;
}
declare module '@codedungeon/gunner/sandbox/core_commands/default.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/core_commands/default'>;
}
declare module '@codedungeon/gunner/sandbox/core_commands/make-command.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/core_commands/make-command'>;
}
declare module '@codedungeon/gunner/sandbox/core_commands/make-extension.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/core_commands/make-extension'>;
}
declare module '@codedungeon/gunner/sandbox/core_commands/new.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/core_commands/new'>;
}
declare module '@codedungeon/gunner/sandbox/core_commands/sayHello.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/core_commands/sayHello'>;
}
declare module '@codedungeon/gunner/sandbox/core_commands/test-prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/core_commands/test-prompt'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/log-keypress.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/log-keypress'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-async.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-async'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-autocomplete.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-autocomplete'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-editable-choices-header.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-editable-choices-header'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-invisible.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-invisible'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-multiple.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-multiple'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-number-multiple.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-number-multiple'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-number.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-number'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-option-async.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-option-async'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-prompt'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-quiz.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-quiz'>;
}
declare module '@codedungeon/gunner/sandbox/prompts/test-snippet.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/prompts/test-snippet'>;
}
declare module '@codedungeon/gunner/sandbox/security/security.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/security/security'>;
}
declare module '@codedungeon/gunner/sandbox/security/security.lib.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/security/security.lib'>;
}
declare module '@codedungeon/gunner/sandbox/security/test-security.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/security/test-security'>;
}
declare module '@codedungeon/gunner/sandbox/templates/test-module.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/templates/test-module'>;
}
declare module '@codedungeon/gunner/sandbox/templates/test.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/templates/test'>;
}
declare module '@codedungeon/gunner/sandbox/test_getOptionValue.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test_getOptionValue'>;
}
declare module '@codedungeon/gunner/sandbox/test-boolean.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-boolean'>;
}
declare module '@codedungeon/gunner/sandbox/test-cli.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-cli'>;
}
declare module '@codedungeon/gunner/sandbox/test-confirm.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-confirm'>;
}
declare module '@codedungeon/gunner/sandbox/test-directoryList.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-directoryList'>;
}
declare module '@codedungeon/gunner/sandbox/test-environment.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-environment'>;
}
declare module '@codedungeon/gunner/sandbox/test-everything.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-everything'>;
}
declare module '@codedungeon/gunner/sandbox/test-form.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-form'>;
}
declare module '@codedungeon/gunner/sandbox/test-fs-promise-async.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-fs-promise-async'>;
}
declare module '@codedungeon/gunner/sandbox/test-fs-promise.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-fs-promise'>;
}
declare module '@codedungeon/gunner/sandbox/test-get-ip.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-get-ip'>;
}
declare module '@codedungeon/gunner/sandbox/test-hooks.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-hooks'>;
}
declare module '@codedungeon/gunner/sandbox/test-print-class.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-print-class'>;
}
declare module '@codedungeon/gunner/sandbox/test-print.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test-print'>;
}
declare module '@codedungeon/gunner/sandbox/test.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/sandbox/test'>;
}
declare module '@codedungeon/gunner/src/commands/default.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/default'>;
}
declare module '@codedungeon/gunner/src/commands/generate-snippet.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/generate-snippet'>;
}
declare module '@codedungeon/gunner/src/commands/make-command.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/make-command'>;
}
declare module '@codedungeon/gunner/src/commands/make-extension.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/make-extension'>;
}
declare module '@codedungeon/gunner/src/commands/new.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/new'>;
}
declare module '@codedungeon/gunner/src/commands/quick-prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/quick-prompt'>;
}
declare module '@codedungeon/gunner/src/commands/sayHello.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/sayHello'>;
}
declare module '@codedungeon/gunner/src/commands/test-prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/commands/test-prompt'>;
}
declare module '@codedungeon/gunner/src/extensions/hello-extension.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/extensions/hello-extension'>;
}
declare module '@codedungeon/gunner/src/extensions/info-extension.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/extensions/info-extension'>;
}
declare module '@codedungeon/gunner/src/gunner.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/gunner'>;
}
declare module '@codedungeon/gunner/src/inspector.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/inspector'>;
}
declare module '@codedungeon/gunner/src/templates/prettier.config.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/templates/prettier.config'>;
}
declare module '@codedungeon/gunner/src/toolbox/api.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/api'>;
}
declare module '@codedungeon/gunner/src/toolbox/app-old.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/app-old'>;
}
declare module '@codedungeon/gunner/src/toolbox/app.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/app'>;
}
declare module '@codedungeon/gunner/src/toolbox/arrays.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/arrays'>;
}
declare module '@codedungeon/gunner/src/toolbox/config.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/config'>;
}
declare module '@codedungeon/gunner/src/toolbox/environment.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/environment'>;
}
declare module '@codedungeon/gunner/src/toolbox/filesystem.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/filesystem'>;
}
declare module '@codedungeon/gunner/src/toolbox/globals.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/globals'>;
}
declare module '@codedungeon/gunner/src/toolbox/helpers.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/helpers'>;
}
declare module '@codedungeon/gunner/src/toolbox/multi-prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/multi-prompt'>;
}
declare module '@codedungeon/gunner/src/toolbox/packageManager.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/packageManager'>;
}
declare module '@codedungeon/gunner/src/toolbox/print.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/print'>;
}
declare module '@codedungeon/gunner/src/toolbox/print2.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/print2'>;
}
declare module '@codedungeon/gunner/src/toolbox/prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/prompt'>;
}
declare module '@codedungeon/gunner/src/toolbox/security.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/security'>;
}
declare module '@codedungeon/gunner/src/toolbox/security.lib.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/security.lib'>;
}
declare module '@codedungeon/gunner/src/toolbox/strings.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/strings'>;
}
declare module '@codedungeon/gunner/src/toolbox/system.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/system'>;
}
declare module '@codedungeon/gunner/src/toolbox/table.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/table'>;
}
declare module '@codedungeon/gunner/src/toolbox/template-eta.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/template-eta'>;
}
declare module '@codedungeon/gunner/src/toolbox/template.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/toolbox/template'>;
}
declare module '@codedungeon/gunner/src/utils/input.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/utils/input'>;
}
declare module '@codedungeon/gunner/src/utils/prompt.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/utils/prompt'>;
}
declare module '@codedungeon/gunner/src/utils/question.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/src/utils/question'>;
}
declare module '@codedungeon/gunner/tasks/bumpBuild.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/tasks/bumpBuild'>;
}
declare module '@codedungeon/gunner/tasks/deploy.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/tasks/deploy'>;
}
declare module '@codedungeon/gunner/tasks/lint.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/tasks/lint'>;
}
declare module '@codedungeon/gunner/tasks/test.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/tasks/test'>;
}
declare module '@codedungeon/gunner/tasks/todo.js' {
  declare module.exports: $Exports<'@codedungeon/gunner/tasks/todo'>;
}
