// flow-typed signature: b49b9bab66715cc78df9d28e685d889f
// flow-typed version: <<STUB>>/bqpjs_v^0.1.1/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bqpjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bqpjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bqpjs/dist/bundle.cjs' {
  declare module.exports: any;
}

declare module 'bqpjs/dist/bundle.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bqpjs/dist/bundle.cjs.js' {
  declare module.exports: $Exports<'bqpjs/dist/bundle.cjs'>;
}
declare module 'bqpjs/dist/bundle.esm.js' {
  declare module.exports: $Exports<'bqpjs/dist/bundle.esm'>;
}
