// flow-typed signature: fd61f7127ab3c239814e52ad29650113
// flow-typed version: <<STUB>>/bump-regex_v4.1.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bump-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bump-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bump-regex/index' {
  declare module.exports: $Exports<'bump-regex'>;
}
declare module 'bump-regex/index.js' {
  declare module.exports: $Exports<'bump-regex'>;
}
