// flow-typed signature: d2d2c489419e985974ac42efbb62c2b2
// flow-typed version: <<STUB>>/commander_v^8.1.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commander'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commander' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commander/lib/argument' {
  declare module.exports: any;
}

declare module 'commander/lib/command' {
  declare module.exports: any;
}

declare module 'commander/lib/error' {
  declare module.exports: any;
}

declare module 'commander/lib/help' {
  declare module.exports: any;
}

declare module 'commander/lib/option' {
  declare module.exports: any;
}

declare module 'commander/lib/suggestSimilar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commander/index' {
  declare module.exports: $Exports<'commander'>;
}
declare module 'commander/index.js' {
  declare module.exports: $Exports<'commander'>;
}
declare module 'commander/lib/argument.js' {
  declare module.exports: $Exports<'commander/lib/argument'>;
}
declare module 'commander/lib/command.js' {
  declare module.exports: $Exports<'commander/lib/command'>;
}
declare module 'commander/lib/error.js' {
  declare module.exports: $Exports<'commander/lib/error'>;
}
declare module 'commander/lib/help.js' {
  declare module.exports: $Exports<'commander/lib/help'>;
}
declare module 'commander/lib/option.js' {
  declare module.exports: $Exports<'commander/lib/option'>;
}
declare module 'commander/lib/suggestSimilar.js' {
  declare module.exports: $Exports<'commander/lib/suggestSimilar'>;
}
