// flow-typed signature: feaadf8df9a088203541504dc49507b0
// flow-typed version: <<STUB>>/contentful-html-rich-text-converter_v1.0.9/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contentful-html-rich-text-converter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contentful-html-rich-text-converter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contentful-html-rich-text-converter/helpers' {
  declare module.exports: any;
}

declare module 'contentful-html-rich-text-converter/helpers/paragraph' {
  declare module.exports: any;
}

declare module 'contentful-html-rich-text-converter/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contentful-html-rich-text-converter/helpers/index' {
  declare module.exports: $Exports<'contentful-html-rich-text-converter/helpers'>;
}
declare module 'contentful-html-rich-text-converter/helpers/index.js' {
  declare module.exports: $Exports<'contentful-html-rich-text-converter/helpers'>;
}
declare module 'contentful-html-rich-text-converter/helpers/paragraph.js' {
  declare module.exports: $Exports<'contentful-html-rich-text-converter/helpers/paragraph'>;
}
declare module 'contentful-html-rich-text-converter/index' {
  declare module.exports: $Exports<'contentful-html-rich-text-converter'>;
}
declare module 'contentful-html-rich-text-converter/index.js' {
  declare module.exports: $Exports<'contentful-html-rich-text-converter'>;
}
declare module 'contentful-html-rich-text-converter/tests/index.test.js' {
  declare module.exports: $Exports<'contentful-html-rich-text-converter/tests/index.test'>;
}
