// flow-typed signature: 4f8761211667b5129909bb0cd97bcf46
// flow-typed version: <<STUB>>/enquirer_v^2.3.6/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enquirer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enquirer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enquirer/lib/ansi' {
  declare module.exports: any;
}

declare module 'enquirer/lib/combos' {
  declare module.exports: any;
}

declare module 'enquirer/lib/completer' {
  declare module.exports: any;
}

declare module 'enquirer/lib/interpolate' {
  declare module.exports: any;
}

declare module 'enquirer/lib/keypress' {
  declare module.exports: any;
}

declare module 'enquirer/lib/placeholder' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompt' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/autocomplete' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/basicauth' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/confirm' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/editable' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/form' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/input' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/invisible' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/list' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/multiselect' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/numeral' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/password' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/quiz' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/scale' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/select' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/snippet' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/sort' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/survey' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/text' {
  declare module.exports: any;
}

declare module 'enquirer/lib/prompts/toggle' {
  declare module.exports: any;
}

declare module 'enquirer/lib/render' {
  declare module.exports: any;
}

declare module 'enquirer/lib/roles' {
  declare module.exports: any;
}

declare module 'enquirer/lib/state' {
  declare module.exports: any;
}

declare module 'enquirer/lib/styles' {
  declare module.exports: any;
}

declare module 'enquirer/lib/symbols' {
  declare module.exports: any;
}

declare module 'enquirer/lib/theme' {
  declare module.exports: any;
}

declare module 'enquirer/lib/timer' {
  declare module.exports: any;
}

declare module 'enquirer/lib/types/array' {
  declare module.exports: any;
}

declare module 'enquirer/lib/types/auth' {
  declare module.exports: any;
}

declare module 'enquirer/lib/types/boolean' {
  declare module.exports: any;
}

declare module 'enquirer/lib/types' {
  declare module.exports: any;
}

declare module 'enquirer/lib/types/number' {
  declare module.exports: any;
}

declare module 'enquirer/lib/types/string' {
  declare module.exports: any;
}

declare module 'enquirer/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enquirer/index' {
  declare module.exports: $Exports<'enquirer'>;
}
declare module 'enquirer/index.js' {
  declare module.exports: $Exports<'enquirer'>;
}
declare module 'enquirer/lib/ansi.js' {
  declare module.exports: $Exports<'enquirer/lib/ansi'>;
}
declare module 'enquirer/lib/combos.js' {
  declare module.exports: $Exports<'enquirer/lib/combos'>;
}
declare module 'enquirer/lib/completer.js' {
  declare module.exports: $Exports<'enquirer/lib/completer'>;
}
declare module 'enquirer/lib/interpolate.js' {
  declare module.exports: $Exports<'enquirer/lib/interpolate'>;
}
declare module 'enquirer/lib/keypress.js' {
  declare module.exports: $Exports<'enquirer/lib/keypress'>;
}
declare module 'enquirer/lib/placeholder.js' {
  declare module.exports: $Exports<'enquirer/lib/placeholder'>;
}
declare module 'enquirer/lib/prompt.js' {
  declare module.exports: $Exports<'enquirer/lib/prompt'>;
}
declare module 'enquirer/lib/prompts/autocomplete.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/autocomplete'>;
}
declare module 'enquirer/lib/prompts/basicauth.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/basicauth'>;
}
declare module 'enquirer/lib/prompts/confirm.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/confirm'>;
}
declare module 'enquirer/lib/prompts/editable.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/editable'>;
}
declare module 'enquirer/lib/prompts/form.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/form'>;
}
declare module 'enquirer/lib/prompts/index' {
  declare module.exports: $Exports<'enquirer/lib/prompts'>;
}
declare module 'enquirer/lib/prompts/index.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts'>;
}
declare module 'enquirer/lib/prompts/input.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/input'>;
}
declare module 'enquirer/lib/prompts/invisible.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/invisible'>;
}
declare module 'enquirer/lib/prompts/list.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/list'>;
}
declare module 'enquirer/lib/prompts/multiselect.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/multiselect'>;
}
declare module 'enquirer/lib/prompts/numeral.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/numeral'>;
}
declare module 'enquirer/lib/prompts/password.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/password'>;
}
declare module 'enquirer/lib/prompts/quiz.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/quiz'>;
}
declare module 'enquirer/lib/prompts/scale.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/scale'>;
}
declare module 'enquirer/lib/prompts/select.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/select'>;
}
declare module 'enquirer/lib/prompts/snippet.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/snippet'>;
}
declare module 'enquirer/lib/prompts/sort.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/sort'>;
}
declare module 'enquirer/lib/prompts/survey.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/survey'>;
}
declare module 'enquirer/lib/prompts/text.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/text'>;
}
declare module 'enquirer/lib/prompts/toggle.js' {
  declare module.exports: $Exports<'enquirer/lib/prompts/toggle'>;
}
declare module 'enquirer/lib/render.js' {
  declare module.exports: $Exports<'enquirer/lib/render'>;
}
declare module 'enquirer/lib/roles.js' {
  declare module.exports: $Exports<'enquirer/lib/roles'>;
}
declare module 'enquirer/lib/state.js' {
  declare module.exports: $Exports<'enquirer/lib/state'>;
}
declare module 'enquirer/lib/styles.js' {
  declare module.exports: $Exports<'enquirer/lib/styles'>;
}
declare module 'enquirer/lib/symbols.js' {
  declare module.exports: $Exports<'enquirer/lib/symbols'>;
}
declare module 'enquirer/lib/theme.js' {
  declare module.exports: $Exports<'enquirer/lib/theme'>;
}
declare module 'enquirer/lib/timer.js' {
  declare module.exports: $Exports<'enquirer/lib/timer'>;
}
declare module 'enquirer/lib/types/array.js' {
  declare module.exports: $Exports<'enquirer/lib/types/array'>;
}
declare module 'enquirer/lib/types/auth.js' {
  declare module.exports: $Exports<'enquirer/lib/types/auth'>;
}
declare module 'enquirer/lib/types/boolean.js' {
  declare module.exports: $Exports<'enquirer/lib/types/boolean'>;
}
declare module 'enquirer/lib/types/index' {
  declare module.exports: $Exports<'enquirer/lib/types'>;
}
declare module 'enquirer/lib/types/index.js' {
  declare module.exports: $Exports<'enquirer/lib/types'>;
}
declare module 'enquirer/lib/types/number.js' {
  declare module.exports: $Exports<'enquirer/lib/types/number'>;
}
declare module 'enquirer/lib/types/string.js' {
  declare module.exports: $Exports<'enquirer/lib/types/string'>;
}
declare module 'enquirer/lib/utils.js' {
  declare module.exports: $Exports<'enquirer/lib/utils'>;
}
