// flow-typed signature: 39f67906f9416ca06e2f5db42bebc017
// flow-typed version: <<STUB>>/eslint-plugin-unused-imports_v1.1.5/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-unused-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-unused-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-unused-imports/lib/__test__/no-unused-imports.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unused-imports/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unused-imports/lib/rules/no-unused-imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unused-imports/lib/rules/no-unused-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unused-imports/lib/rules/predicates' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-unused-imports/lib/__test__/no-unused-imports.test.js' {
  declare module.exports: $Exports<'eslint-plugin-unused-imports/lib/__test__/no-unused-imports.test'>;
}
declare module 'eslint-plugin-unused-imports/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-unused-imports/lib'>;
}
declare module 'eslint-plugin-unused-imports/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-unused-imports/lib'>;
}
declare module 'eslint-plugin-unused-imports/lib/rules/no-unused-imports.js' {
  declare module.exports: $Exports<'eslint-plugin-unused-imports/lib/rules/no-unused-imports'>;
}
declare module 'eslint-plugin-unused-imports/lib/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-unused-imports/lib/rules/no-unused-vars'>;
}
declare module 'eslint-plugin-unused-imports/lib/rules/predicates.js' {
  declare module.exports: $Exports<'eslint-plugin-unused-imports/lib/rules/predicates'>;
}
