// flow-typed signature: 48185b65c21f85102bd1627da4ef2be6
// flow-typed version: <<STUB>>/findup-sync_v4.0.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'findup-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'findup-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'findup-sync/index' {
  declare module.exports: $Exports<'findup-sync'>;
}
declare module 'findup-sync/index.js' {
  declare module.exports: $Exports<'findup-sync'>;
}
