// flow-typed signature: 4c6ee41a7411af46fbc1d389684e0024
// flow-typed version: <<STUB>>/fuse.js_v^6.5.3/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuse.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuse.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fuse.js/dist/fuse.basic.common' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.basic.esm' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.basic.esm.min' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.basic' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.basic.min' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.common' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.esm' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.esm.min' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse' {
  declare module.exports: any;
}

declare module 'fuse.js/dist/fuse.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fuse.js/dist/fuse.basic.common.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.basic.common'>;
}
declare module 'fuse.js/dist/fuse.basic.esm.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.basic.esm'>;
}
declare module 'fuse.js/dist/fuse.basic.esm.min.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.basic.esm.min'>;
}
declare module 'fuse.js/dist/fuse.basic.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.basic'>;
}
declare module 'fuse.js/dist/fuse.basic.min.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.basic.min'>;
}
declare module 'fuse.js/dist/fuse.common.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.common'>;
}
declare module 'fuse.js/dist/fuse.esm.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.esm'>;
}
declare module 'fuse.js/dist/fuse.esm.min.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.esm.min'>;
}
declare module 'fuse.js/dist/fuse.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse'>;
}
declare module 'fuse.js/dist/fuse.min.js' {
  declare module.exports: $Exports<'fuse.js/dist/fuse.min'>;
}
