// flow-typed signature: 19a698518e8a65912ff1e8559da2cfb6
// flow-typed version: <<STUB>>/git-state_v4.1.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-state/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-state/index' {
  declare module.exports: $Exports<'git-state'>;
}
declare module 'git-state/index.js' {
  declare module.exports: $Exports<'git-state'>;
}
declare module 'git-state/test.js' {
  declare module.exports: $Exports<'git-state/test'>;
}
