// flow-typed signature: 3dc6529c0a2a7882f6c62064fa8c5194
// flow-typed version: <<STUB>>/jest-silent-reporter_v^0.5.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-silent-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-silent-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-silent-reporter/helpers' {
  declare module.exports: any;
}

declare module 'jest-silent-reporter/SilentReporter' {
  declare module.exports: any;
}

declare module 'jest-silent-reporter/StdIo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-silent-reporter/helpers.js' {
  declare module.exports: $Exports<'jest-silent-reporter/helpers'>;
}
declare module 'jest-silent-reporter/index' {
  declare module.exports: $Exports<'jest-silent-reporter'>;
}
declare module 'jest-silent-reporter/index.js' {
  declare module.exports: $Exports<'jest-silent-reporter'>;
}
declare module 'jest-silent-reporter/SilentReporter.js' {
  declare module.exports: $Exports<'jest-silent-reporter/SilentReporter'>;
}
declare module 'jest-silent-reporter/StdIo.js' {
  declare module.exports: $Exports<'jest-silent-reporter/StdIo'>;
}
