// flow-typed signature: 1d34eb2bef743e64435abd287199eaa8
// flow-typed version: <<STUB>>/jest-spec-reporter_v1.0.17/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-spec-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-spec-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-spec-reporter/example/example.spec' {
  declare module.exports: any;
}

declare module 'jest-spec-reporter/example/jest.config' {
  declare module.exports: any;
}

declare module 'jest-spec-reporter/lib' {
  declare module.exports: any;
}

declare module 'jest-spec-reporter/lib/jest-spec-reporter' {
  declare module.exports: any;
}

declare module 'jest-spec-reporter/lib/jest-spec-reporter.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-spec-reporter/example/example.spec.js' {
  declare module.exports: $Exports<'jest-spec-reporter/example/example.spec'>;
}
declare module 'jest-spec-reporter/example/jest.config.js' {
  declare module.exports: $Exports<'jest-spec-reporter/example/jest.config'>;
}
declare module 'jest-spec-reporter/lib/index' {
  declare module.exports: $Exports<'jest-spec-reporter/lib'>;
}
declare module 'jest-spec-reporter/lib/index.js' {
  declare module.exports: $Exports<'jest-spec-reporter/lib'>;
}
declare module 'jest-spec-reporter/lib/jest-spec-reporter.js' {
  declare module.exports: $Exports<'jest-spec-reporter/lib/jest-spec-reporter'>;
}
declare module 'jest-spec-reporter/lib/jest-spec-reporter.spec.js' {
  declare module.exports: $Exports<'jest-spec-reporter/lib/jest-spec-reporter.spec'>;
}
