// flow-typed signature: 373b3e80bd04e9231f71f8df648bc6e7
// flow-typed version: <<STUB>>/luxon_v^2.4.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luxon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'luxon' {
  declare module.exports: any;
}
