// flow-typed signature: df70f956c9be2d1e03a31b329526c273
// flow-typed version: <<STUB>>/luxon-business-days_v^2.8.3/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luxon-business-days'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'luxon-business-days' {
  declare module.exports: any;
}
