// flow-typed signature: 7b3ffc05b6f831f13af71c6850db5729
// flow-typed version: <<STUB>>/moment-business-days_v1.2.0/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-business-days'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-business-days' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-business-days/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-business-days/index' {
  declare module.exports: $Exports<'moment-business-days'>;
}
declare module 'moment-business-days/index.js' {
  declare module.exports: $Exports<'moment-business-days'>;
}
declare module 'moment-business-days/tests/test.js' {
  declare module.exports: $Exports<'moment-business-days/tests/test'>;
}
