// flow-typed signature: 1a661a7d9dac8515d4f83810894fc4b6
// flow-typed version: <<STUB>>/node-libcurl_v2.3.3/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-libcurl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-libcurl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-libcurl/commitlint.config' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/Curl' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/curly' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/Easy' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlAuth' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlChunk' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlCode' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlFeature' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlFileType' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlFnMatchFunc' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlFtpMethod' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlFtpSsl' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlGlobalInit' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlGssApi' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlHeader' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlHttpVersion' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlInfoDebug' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlIpResolve' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlNetrc' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlPause' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlPipe' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlProgressFunc' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlProtocol' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlProxy' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlPush' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlPx' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlReadFunc' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlRtspRequest' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlShareLock' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlShareOption' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlSshAuth' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlSslOpt' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlSslVersion' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlTimeCond' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlUseSsl' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlVersion' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/CurlWriteFunc' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/enum/SocketState' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/generated/CurlInfo' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/generated/CurlOption' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/generated/MultiOption' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/mergeChunks' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/Multi' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/parseHeaders' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/Share' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/CurlNativeBinding' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/CurlVersionInfoNativeBinding' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/EasyNativeBinding' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/FileInfo' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/Http2PushFrameHeaders' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/HttpPostField' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/MultiNativeBinding' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/NodeLibcurlNativeBinding' {
  declare module.exports: any;
}

declare module 'node-libcurl/dist/types/ShareNativeBinding' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/build-constants' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/cpp-std' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/curl-config' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/data/options' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/module-packaging' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/retrieve-win-deps' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/update-deps' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/buildFlags' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/convertCurlConstantToCamelCase' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/createConstantsFile' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/createSetOptOverloads' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/curlOptionsBlacklist' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/multiOptionsBlacklist' {
  declare module.exports: any;
}

declare module 'node-libcurl/scripts/utils/retrieveConstantList' {
  declare module.exports: any;
}

declare module 'node-libcurl/tools/brute-force-leak-test-multi' {
  declare module.exports: any;
}

declare module 'node-libcurl/tools/brute-force-leak-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-libcurl/commitlint.config.js' {
  declare module.exports: $Exports<'node-libcurl/commitlint.config'>;
}
declare module 'node-libcurl/dist/Curl.js' {
  declare module.exports: $Exports<'node-libcurl/dist/Curl'>;
}
declare module 'node-libcurl/dist/curly.js' {
  declare module.exports: $Exports<'node-libcurl/dist/curly'>;
}
declare module 'node-libcurl/dist/Easy.js' {
  declare module.exports: $Exports<'node-libcurl/dist/Easy'>;
}
declare module 'node-libcurl/dist/enum/CurlAuth.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlAuth'>;
}
declare module 'node-libcurl/dist/enum/CurlChunk.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlChunk'>;
}
declare module 'node-libcurl/dist/enum/CurlCode.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlCode'>;
}
declare module 'node-libcurl/dist/enum/CurlFeature.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlFeature'>;
}
declare module 'node-libcurl/dist/enum/CurlFileType.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlFileType'>;
}
declare module 'node-libcurl/dist/enum/CurlFnMatchFunc.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlFnMatchFunc'>;
}
declare module 'node-libcurl/dist/enum/CurlFtpMethod.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlFtpMethod'>;
}
declare module 'node-libcurl/dist/enum/CurlFtpSsl.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlFtpSsl'>;
}
declare module 'node-libcurl/dist/enum/CurlGlobalInit.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlGlobalInit'>;
}
declare module 'node-libcurl/dist/enum/CurlGssApi.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlGssApi'>;
}
declare module 'node-libcurl/dist/enum/CurlHeader.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlHeader'>;
}
declare module 'node-libcurl/dist/enum/CurlHttpVersion.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlHttpVersion'>;
}
declare module 'node-libcurl/dist/enum/CurlInfoDebug.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlInfoDebug'>;
}
declare module 'node-libcurl/dist/enum/CurlIpResolve.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlIpResolve'>;
}
declare module 'node-libcurl/dist/enum/CurlNetrc.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlNetrc'>;
}
declare module 'node-libcurl/dist/enum/CurlPause.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlPause'>;
}
declare module 'node-libcurl/dist/enum/CurlPipe.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlPipe'>;
}
declare module 'node-libcurl/dist/enum/CurlProgressFunc.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlProgressFunc'>;
}
declare module 'node-libcurl/dist/enum/CurlProtocol.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlProtocol'>;
}
declare module 'node-libcurl/dist/enum/CurlProxy.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlProxy'>;
}
declare module 'node-libcurl/dist/enum/CurlPush.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlPush'>;
}
declare module 'node-libcurl/dist/enum/CurlPx.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlPx'>;
}
declare module 'node-libcurl/dist/enum/CurlReadFunc.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlReadFunc'>;
}
declare module 'node-libcurl/dist/enum/CurlRtspRequest.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlRtspRequest'>;
}
declare module 'node-libcurl/dist/enum/CurlShareLock.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlShareLock'>;
}
declare module 'node-libcurl/dist/enum/CurlShareOption.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlShareOption'>;
}
declare module 'node-libcurl/dist/enum/CurlSshAuth.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlSshAuth'>;
}
declare module 'node-libcurl/dist/enum/CurlSslOpt.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlSslOpt'>;
}
declare module 'node-libcurl/dist/enum/CurlSslVersion.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlSslVersion'>;
}
declare module 'node-libcurl/dist/enum/CurlTimeCond.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlTimeCond'>;
}
declare module 'node-libcurl/dist/enum/CurlUseSsl.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlUseSsl'>;
}
declare module 'node-libcurl/dist/enum/CurlVersion.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlVersion'>;
}
declare module 'node-libcurl/dist/enum/CurlWriteFunc.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/CurlWriteFunc'>;
}
declare module 'node-libcurl/dist/enum/SocketState.js' {
  declare module.exports: $Exports<'node-libcurl/dist/enum/SocketState'>;
}
declare module 'node-libcurl/dist/generated/CurlInfo.js' {
  declare module.exports: $Exports<'node-libcurl/dist/generated/CurlInfo'>;
}
declare module 'node-libcurl/dist/generated/CurlOption.js' {
  declare module.exports: $Exports<'node-libcurl/dist/generated/CurlOption'>;
}
declare module 'node-libcurl/dist/generated/MultiOption.js' {
  declare module.exports: $Exports<'node-libcurl/dist/generated/MultiOption'>;
}
declare module 'node-libcurl/dist/index' {
  declare module.exports: $Exports<'node-libcurl/dist'>;
}
declare module 'node-libcurl/dist/index.js' {
  declare module.exports: $Exports<'node-libcurl/dist'>;
}
declare module 'node-libcurl/dist/mergeChunks.js' {
  declare module.exports: $Exports<'node-libcurl/dist/mergeChunks'>;
}
declare module 'node-libcurl/dist/Multi.js' {
  declare module.exports: $Exports<'node-libcurl/dist/Multi'>;
}
declare module 'node-libcurl/dist/parseHeaders.js' {
  declare module.exports: $Exports<'node-libcurl/dist/parseHeaders'>;
}
declare module 'node-libcurl/dist/Share.js' {
  declare module.exports: $Exports<'node-libcurl/dist/Share'>;
}
declare module 'node-libcurl/dist/types/CurlNativeBinding.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/CurlNativeBinding'>;
}
declare module 'node-libcurl/dist/types/CurlVersionInfoNativeBinding.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/CurlVersionInfoNativeBinding'>;
}
declare module 'node-libcurl/dist/types/EasyNativeBinding.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/EasyNativeBinding'>;
}
declare module 'node-libcurl/dist/types/FileInfo.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/FileInfo'>;
}
declare module 'node-libcurl/dist/types/Http2PushFrameHeaders.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/Http2PushFrameHeaders'>;
}
declare module 'node-libcurl/dist/types/HttpPostField.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/HttpPostField'>;
}
declare module 'node-libcurl/dist/types/index' {
  declare module.exports: $Exports<'node-libcurl/dist/types'>;
}
declare module 'node-libcurl/dist/types/index.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types'>;
}
declare module 'node-libcurl/dist/types/MultiNativeBinding.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/MultiNativeBinding'>;
}
declare module 'node-libcurl/dist/types/NodeLibcurlNativeBinding.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/NodeLibcurlNativeBinding'>;
}
declare module 'node-libcurl/dist/types/ShareNativeBinding.js' {
  declare module.exports: $Exports<'node-libcurl/dist/types/ShareNativeBinding'>;
}
declare module 'node-libcurl/scripts/build-constants.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/build-constants'>;
}
declare module 'node-libcurl/scripts/cpp-std.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/cpp-std'>;
}
declare module 'node-libcurl/scripts/curl-config.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/curl-config'>;
}
declare module 'node-libcurl/scripts/data/options.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/data/options'>;
}
declare module 'node-libcurl/scripts/module-packaging.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/module-packaging'>;
}
declare module 'node-libcurl/scripts/postinstall.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/postinstall'>;
}
declare module 'node-libcurl/scripts/retrieve-win-deps.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/retrieve-win-deps'>;
}
declare module 'node-libcurl/scripts/update-deps.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/update-deps'>;
}
declare module 'node-libcurl/scripts/utils/buildFlags.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/buildFlags'>;
}
declare module 'node-libcurl/scripts/utils/convertCurlConstantToCamelCase.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/convertCurlConstantToCamelCase'>;
}
declare module 'node-libcurl/scripts/utils/createConstantsFile.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/createConstantsFile'>;
}
declare module 'node-libcurl/scripts/utils/createSetOptOverloads.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/createSetOptOverloads'>;
}
declare module 'node-libcurl/scripts/utils/curlOptionsBlacklist.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/curlOptionsBlacklist'>;
}
declare module 'node-libcurl/scripts/utils/multiOptionsBlacklist.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/multiOptionsBlacklist'>;
}
declare module 'node-libcurl/scripts/utils/retrieveConstantList.js' {
  declare module.exports: $Exports<'node-libcurl/scripts/utils/retrieveConstantList'>;
}
declare module 'node-libcurl/tools/brute-force-leak-test-multi.js' {
  declare module.exports: $Exports<'node-libcurl/tools/brute-force-leak-test-multi'>;
}
declare module 'node-libcurl/tools/brute-force-leak-test.js' {
  declare module.exports: $Exports<'node-libcurl/tools/brute-force-leak-test'>;
}
