// flow-typed signature: fc5e5d012098e702ff0b50db8671b94f
// flow-typed version: <<STUB>>/node-notifier_v10.0.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-notifier/lib/checkGrowl' {
  declare module.exports: any;
}

declare module 'node-notifier/lib/utils' {
  declare module.exports: any;
}

declare module 'node-notifier/notifiers/balloon' {
  declare module.exports: any;
}

declare module 'node-notifier/notifiers/growl' {
  declare module.exports: any;
}

declare module 'node-notifier/notifiers/notificationcenter' {
  declare module.exports: any;
}

declare module 'node-notifier/notifiers/notifysend' {
  declare module.exports: any;
}

declare module 'node-notifier/notifiers/toaster' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-notifier/index' {
  declare module.exports: $Exports<'node-notifier'>;
}
declare module 'node-notifier/index.js' {
  declare module.exports: $Exports<'node-notifier'>;
}
declare module 'node-notifier/lib/checkGrowl.js' {
  declare module.exports: $Exports<'node-notifier/lib/checkGrowl'>;
}
declare module 'node-notifier/lib/utils.js' {
  declare module.exports: $Exports<'node-notifier/lib/utils'>;
}
declare module 'node-notifier/notifiers/balloon.js' {
  declare module.exports: $Exports<'node-notifier/notifiers/balloon'>;
}
declare module 'node-notifier/notifiers/growl.js' {
  declare module.exports: $Exports<'node-notifier/notifiers/growl'>;
}
declare module 'node-notifier/notifiers/notificationcenter.js' {
  declare module.exports: $Exports<'node-notifier/notifiers/notificationcenter'>;
}
declare module 'node-notifier/notifiers/notifysend.js' {
  declare module.exports: $Exports<'node-notifier/notifiers/notifysend'>;
}
declare module 'node-notifier/notifiers/toaster.js' {
  declare module.exports: $Exports<'node-notifier/notifiers/toaster'>;
}
