// flow-typed signature: 3eed4184d04bc11b994733329e8d5a68
// flow-typed version: <<STUB>>/react-data-table-component_v^7.5.3/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-data-table-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-data-table-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-data-table-component/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-data-table-component/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-data-table-component/dist/react-data-table-component.dev' {
  declare module.exports: any;
}

declare module 'react-data-table-component/dist/react-data-table-component.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-data-table-component/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-data-table-component/dist/index.cjs'>;
}
declare module 'react-data-table-component/dist/index.es.js' {
  declare module.exports: $Exports<'react-data-table-component/dist/index.es'>;
}
declare module 'react-data-table-component/dist/react-data-table-component.dev.js' {
  declare module.exports: $Exports<'react-data-table-component/dist/react-data-table-component.dev'>;
}
declare module 'react-data-table-component/dist/react-data-table-component.umd.js' {
  declare module.exports: $Exports<'react-data-table-component/dist/react-data-table-component.umd'>;
}
