// flow-typed signature: 55ff36056d2240c2138fd61c1353f715
// flow-typed version: <<STUB>>/react-error-boundary_v^3.1.4/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-error-boundary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-error-boundary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-error-boundary/dist/react-error-boundary.cjs' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/react-error-boundary.esm' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/react-error-boundary.umd' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/react-error-boundary.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-error-boundary/dist/react-error-boundary.cjs.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.cjs'>;
}
declare module 'react-error-boundary/dist/react-error-boundary.esm.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.esm'>;
}
declare module 'react-error-boundary/dist/react-error-boundary.umd.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.umd'>;
}
declare module 'react-error-boundary/dist/react-error-boundary.umd.min.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.umd.min'>;
}
