// flow-typed signature: 99583bb90138002eb211a2ad3aded916
// flow-typed version: <<STUB>>/showdown_v1.9.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'showdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'showdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'showdown/bin/showdown' {
  declare module.exports: any;
}

declare module 'showdown/dist/showdown' {
  declare module.exports: any;
}

declare module 'showdown/dist/showdown.min' {
  declare module.exports: any;
}

declare module 'showdown/Gruntfile' {
  declare module.exports: any;
}

declare module 'showdown/src/cli/cli' {
  declare module.exports: any;
}

declare module 'showdown/src/cli/makehtml.cmd' {
  declare module.exports: any;
}

declare module 'showdown/src/cli/messenger' {
  declare module.exports: any;
}

declare module 'showdown/src/converter' {
  declare module.exports: any;
}

declare module 'showdown/src/helpers' {
  declare module.exports: any;
}

declare module 'showdown/src/loader' {
  declare module.exports: any;
}

declare module 'showdown/src/options' {
  declare module.exports: any;
}

declare module 'showdown/src/showdown' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/anchors' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/autoLinks' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/blockGamut' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/blockQuotes' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/codeBlocks' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/codeSpans' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/completeHTMLDocument' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/detab' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/ellipsis' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/emoji' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/encodeAmpsAndAngles' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/encodeBackslashEscapes' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/encodeCode' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/escapeSpecialCharsWithinTagAttributes' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/githubCodeBlocks' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/hashBlock' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/hashCodeTags' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/hashElement' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/hashHTMLBlocks' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/hashHTMLSpans' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/hashPreCodeTags' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/headers' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/horizontalRule' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/images' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/italicsAndBold' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/lists' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/blockquote' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/codeBlock' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/codeSpan' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/emphasis' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/header' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/hr' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/image' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/links' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/list' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/listItem' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/node' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/paragraph' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/pre' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/strikethrough' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/strong' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/table' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/tableCell' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/makeMarkdown/txt' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/metadata' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/outdent' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/paragraphs' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/runExtension' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/spanGamut' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/strikethrough' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/stripLinkDefinitions' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/tables' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/underline' {
  declare module.exports: any;
}

declare module 'showdown/src/subParsers/unescapeSpecialChars' {
  declare module.exports: any;
}

declare module 'showdown/test/bootstrap' {
  declare module.exports: any;
}

declare module 'showdown/test/node/cli' {
  declare module.exports: any;
}

declare module 'showdown/test/node/performance' {
  declare module.exports: any;
}

declare module 'showdown/test/node/showdown.Converter' {
  declare module.exports: any;
}

declare module 'showdown/test/node/showdown.Converter.makeHtml' {
  declare module.exports: any;
}

declare module 'showdown/test/node/showdown.Converter.makeMarkdown' {
  declare module.exports: any;
}

declare module 'showdown/test/node/showdown.helpers' {
  declare module.exports: any;
}

declare module 'showdown/test/node/showdown' {
  declare module.exports: any;
}

declare module 'showdown/test/node/testsuite.features' {
  declare module.exports: any;
}

declare module 'showdown/test/node/testsuite.ghost' {
  declare module.exports: any;
}

declare module 'showdown/test/node/testsuite.issues' {
  declare module.exports: any;
}

declare module 'showdown/test/node/testsuite.karlcow' {
  declare module.exports: any;
}

declare module 'showdown/test/node/testsuite.makemd' {
  declare module.exports: any;
}

declare module 'showdown/test/node/testsuite.standard' {
  declare module.exports: any;
}

declare module 'showdown/test/optionswp' {
  declare module.exports: any;
}

declare module 'showdown/test/performance/performance' {
  declare module.exports: any;
}

// Filename aliases
declare module 'showdown/bin/showdown.js' {
  declare module.exports: $Exports<'showdown/bin/showdown'>;
}
declare module 'showdown/dist/showdown.js' {
  declare module.exports: $Exports<'showdown/dist/showdown'>;
}
declare module 'showdown/dist/showdown.min.js' {
  declare module.exports: $Exports<'showdown/dist/showdown.min'>;
}
declare module 'showdown/Gruntfile.js' {
  declare module.exports: $Exports<'showdown/Gruntfile'>;
}
declare module 'showdown/src/cli/cli.js' {
  declare module.exports: $Exports<'showdown/src/cli/cli'>;
}
declare module 'showdown/src/cli/makehtml.cmd.js' {
  declare module.exports: $Exports<'showdown/src/cli/makehtml.cmd'>;
}
declare module 'showdown/src/cli/messenger.js' {
  declare module.exports: $Exports<'showdown/src/cli/messenger'>;
}
declare module 'showdown/src/converter.js' {
  declare module.exports: $Exports<'showdown/src/converter'>;
}
declare module 'showdown/src/helpers.js' {
  declare module.exports: $Exports<'showdown/src/helpers'>;
}
declare module 'showdown/src/loader.js' {
  declare module.exports: $Exports<'showdown/src/loader'>;
}
declare module 'showdown/src/options.js' {
  declare module.exports: $Exports<'showdown/src/options'>;
}
declare module 'showdown/src/showdown.js' {
  declare module.exports: $Exports<'showdown/src/showdown'>;
}
declare module 'showdown/src/subParsers/anchors.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/anchors'>;
}
declare module 'showdown/src/subParsers/autoLinks.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/autoLinks'>;
}
declare module 'showdown/src/subParsers/blockGamut.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/blockGamut'>;
}
declare module 'showdown/src/subParsers/blockQuotes.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/blockQuotes'>;
}
declare module 'showdown/src/subParsers/codeBlocks.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/codeBlocks'>;
}
declare module 'showdown/src/subParsers/codeSpans.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/codeSpans'>;
}
declare module 'showdown/src/subParsers/completeHTMLDocument.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/completeHTMLDocument'>;
}
declare module 'showdown/src/subParsers/detab.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/detab'>;
}
declare module 'showdown/src/subParsers/ellipsis.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/ellipsis'>;
}
declare module 'showdown/src/subParsers/emoji.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/emoji'>;
}
declare module 'showdown/src/subParsers/encodeAmpsAndAngles.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/encodeAmpsAndAngles'>;
}
declare module 'showdown/src/subParsers/encodeBackslashEscapes.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/encodeBackslashEscapes'>;
}
declare module 'showdown/src/subParsers/encodeCode.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/encodeCode'>;
}
declare module 'showdown/src/subParsers/escapeSpecialCharsWithinTagAttributes.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/escapeSpecialCharsWithinTagAttributes'>;
}
declare module 'showdown/src/subParsers/githubCodeBlocks.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/githubCodeBlocks'>;
}
declare module 'showdown/src/subParsers/hashBlock.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/hashBlock'>;
}
declare module 'showdown/src/subParsers/hashCodeTags.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/hashCodeTags'>;
}
declare module 'showdown/src/subParsers/hashElement.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/hashElement'>;
}
declare module 'showdown/src/subParsers/hashHTMLBlocks.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/hashHTMLBlocks'>;
}
declare module 'showdown/src/subParsers/hashHTMLSpans.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/hashHTMLSpans'>;
}
declare module 'showdown/src/subParsers/hashPreCodeTags.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/hashPreCodeTags'>;
}
declare module 'showdown/src/subParsers/headers.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/headers'>;
}
declare module 'showdown/src/subParsers/horizontalRule.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/horizontalRule'>;
}
declare module 'showdown/src/subParsers/images.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/images'>;
}
declare module 'showdown/src/subParsers/italicsAndBold.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/italicsAndBold'>;
}
declare module 'showdown/src/subParsers/lists.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/lists'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/blockquote.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/blockquote'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/codeBlock.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/codeBlock'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/codeSpan.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/codeSpan'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/emphasis.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/emphasis'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/header.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/header'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/hr.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/hr'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/image.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/image'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/links.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/links'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/list.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/list'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/listItem.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/listItem'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/node.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/node'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/paragraph.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/paragraph'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/pre.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/pre'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/strikethrough.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/strikethrough'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/strong.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/strong'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/table.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/table'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/tableCell.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/tableCell'>;
}
declare module 'showdown/src/subParsers/makeMarkdown/txt.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/makeMarkdown/txt'>;
}
declare module 'showdown/src/subParsers/metadata.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/metadata'>;
}
declare module 'showdown/src/subParsers/outdent.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/outdent'>;
}
declare module 'showdown/src/subParsers/paragraphs.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/paragraphs'>;
}
declare module 'showdown/src/subParsers/runExtension.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/runExtension'>;
}
declare module 'showdown/src/subParsers/spanGamut.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/spanGamut'>;
}
declare module 'showdown/src/subParsers/strikethrough.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/strikethrough'>;
}
declare module 'showdown/src/subParsers/stripLinkDefinitions.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/stripLinkDefinitions'>;
}
declare module 'showdown/src/subParsers/tables.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/tables'>;
}
declare module 'showdown/src/subParsers/underline.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/underline'>;
}
declare module 'showdown/src/subParsers/unescapeSpecialChars.js' {
  declare module.exports: $Exports<'showdown/src/subParsers/unescapeSpecialChars'>;
}
declare module 'showdown/test/bootstrap.js' {
  declare module.exports: $Exports<'showdown/test/bootstrap'>;
}
declare module 'showdown/test/node/cli.js' {
  declare module.exports: $Exports<'showdown/test/node/cli'>;
}
declare module 'showdown/test/node/performance.js' {
  declare module.exports: $Exports<'showdown/test/node/performance'>;
}
declare module 'showdown/test/node/showdown.Converter.js' {
  declare module.exports: $Exports<'showdown/test/node/showdown.Converter'>;
}
declare module 'showdown/test/node/showdown.Converter.makeHtml.js' {
  declare module.exports: $Exports<'showdown/test/node/showdown.Converter.makeHtml'>;
}
declare module 'showdown/test/node/showdown.Converter.makeMarkdown.js' {
  declare module.exports: $Exports<'showdown/test/node/showdown.Converter.makeMarkdown'>;
}
declare module 'showdown/test/node/showdown.helpers.js' {
  declare module.exports: $Exports<'showdown/test/node/showdown.helpers'>;
}
declare module 'showdown/test/node/showdown.js' {
  declare module.exports: $Exports<'showdown/test/node/showdown'>;
}
declare module 'showdown/test/node/testsuite.features.js' {
  declare module.exports: $Exports<'showdown/test/node/testsuite.features'>;
}
declare module 'showdown/test/node/testsuite.ghost.js' {
  declare module.exports: $Exports<'showdown/test/node/testsuite.ghost'>;
}
declare module 'showdown/test/node/testsuite.issues.js' {
  declare module.exports: $Exports<'showdown/test/node/testsuite.issues'>;
}
declare module 'showdown/test/node/testsuite.karlcow.js' {
  declare module.exports: $Exports<'showdown/test/node/testsuite.karlcow'>;
}
declare module 'showdown/test/node/testsuite.makemd.js' {
  declare module.exports: $Exports<'showdown/test/node/testsuite.makemd'>;
}
declare module 'showdown/test/node/testsuite.standard.js' {
  declare module.exports: $Exports<'showdown/test/node/testsuite.standard'>;
}
declare module 'showdown/test/optionswp.js' {
  declare module.exports: $Exports<'showdown/test/optionswp'>;
}
declare module 'showdown/test/performance/performance.js' {
  declare module.exports: $Exports<'showdown/test/performance/performance'>;
}
