// flow-typed signature: e6adf14af708b906da7c9e5f177956a6
// flow-typed version: <<STUB>>/simple-input_v^1.0.1/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-input/simple-input' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-input/simple-input.js' {
  declare module.exports: $Exports<'simple-input/simple-input'>;
}
