// flow-typed signature: f6b813f1d3707bb24be62151864fb08f
// flow-typed version: <<STUB>>/toml_v^3.0.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toml' {
  declare export default {
    parse: (string) => mixed,
    stringify: (mixed) => string,
  };
}
