// flow-typed signature: 68e0a3f9993edcfd951ad26a410cae30
// flow-typed version: <<STUB>>/yaml_v^1.10.2/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml' {
  declare export default {
    parse: (string) => mixed,
    stringify: (mixed) => string,
  };
}
