// flow-typed signature: f104d581d2117d07f280414e371ffd01
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.14.3/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
