// flow-typed signature: 3758c093b6326e5113d0e635a31c4f5e
// flow-typed version: <<STUB>>/chrono-node_v^2.6.3/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrono-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrono-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrono-node/dist/cjs/calculation/mergingCalculation' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/calculation/years' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/chrono' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/abstractRefiners' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/calculation/weekdays' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/casualReferences' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/parsers/AbstractParserWithWordBoundary' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/parsers/AbstractTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/parsers/ISOFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/parsers/SlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/AbstractMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/AbstractMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/ExtractTimezoneAbbrRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/ExtractTimezoneOffsetRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/ForwardDateRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/MergeWeekdayComponentRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/OverlapRemovalRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/common/refiners/UnlikelyFormatFilter' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/configurations' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/debugging' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DECasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DECasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DEMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DESpecificTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DETimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DETimeUnitRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DETimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/parsers/DEWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/refiners/DEMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/de/refiners/DEMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENCasualYearMonthDayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameMiddleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENRelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENSlashMonthFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitLaterFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/parsers/ENWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/refiners/ENMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/refiners/ENMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/en/refiners/ENMergeRelativeDateRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/parsers/ESCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/parsers/ESCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/parsers/ESMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/parsers/ESTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/parsers/ESTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/parsers/ESWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/refiners/ESMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/es/refiners/ESMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRSpecificTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/refiners/FRMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/fr/refiners/FRMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ja/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ja' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ja/parsers/JPCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ja/parsers/JPStandardParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ja/refiners/JPMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualDateTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualYearMonthDayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLMonthNameMiddleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLRelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLSlashMonthFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitLaterFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/refiners/NLMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/nl/refiners/NLMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/refiners/PTMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/pt/refiners/PTMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RURelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/refiners/RUMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/ru/refiners/RUMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansRelationWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/refiners/ZHHansMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hans/refiners/ZHHansMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantRelationWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/refiners/ZHHantMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh/hant/refiners/ZHHantMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/locales/zh' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/results' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/timezone' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/utils/dayjs' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/utils/pattern' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/cjs/utils/timeunits' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/calculation/mergingCalculation' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/calculation/years' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/chrono' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/abstractRefiners' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/calculation/weekdays' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/casualReferences' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/parsers/AbstractParserWithWordBoundary' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/parsers/AbstractTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/parsers/ISOFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/parsers/SlashDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/AbstractMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/AbstractMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/ExtractTimezoneAbbrRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/ExtractTimezoneOffsetRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/ForwardDateRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/MergeWeekdayComponentRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/OverlapRemovalRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/common/refiners/UnlikelyFormatFilter' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/configurations' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/debugging' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DECasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DECasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DEMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DESpecificTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DETimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DETimeUnitRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DETimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/parsers/DEWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/refiners/DEMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/de/refiners/DEMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENCasualYearMonthDayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENMonthNameMiddleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENRelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENSlashMonthFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitLaterFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/parsers/ENWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/refiners/ENMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/refiners/ENMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/en/refiners/ENMergeRelativeDateRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/parsers/ESCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/parsers/ESCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/parsers/ESMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/parsers/ESTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/parsers/ESTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/parsers/ESWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/refiners/ESMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/es/refiners/ESMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRSpecificTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/parsers/FRWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/refiners/FRMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/fr/refiners/FRMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ja/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ja' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ja/parsers/JPCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ja/parsers/JPStandardParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ja/refiners/JPMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualDateTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualYearMonthDayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLMonthNameMiddleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLRelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLSlashMonthFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitLaterFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/parsers/NLWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/refiners/NLMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/nl/refiners/NLMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/parsers/PTCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/parsers/PTCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/parsers/PTMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/parsers/PTTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/parsers/PTWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/refiners/PTMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/pt/refiners/PTMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUCasualTimeParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUMonthNameLittleEndianParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUMonthNameParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RURelativeDateFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitAgoFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitWithinFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/parsers/RUWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/refiners/RUMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/ru/refiners/RUMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansRelationWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/refiners/ZHHansMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hans/refiners/ZHHansMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/constants' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantCasualDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantDateParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantDeadlineFormatParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantRelationWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantTimeExpressionParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantWeekdayParser' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/refiners/ZHHantMergeDateRangeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh/hant/refiners/ZHHantMergeDateTimeRefiner' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/locales/zh' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/results' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/timezone' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/utils/dayjs' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/utils/pattern' {
  declare module.exports: any;
}

declare module 'chrono-node/dist/esm/utils/timeunits' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrono-node/dist/cjs/calculation/mergingCalculation.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/calculation/mergingCalculation'>;
}
declare module 'chrono-node/dist/cjs/calculation/years.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/calculation/years'>;
}
declare module 'chrono-node/dist/cjs/chrono.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/chrono'>;
}
declare module 'chrono-node/dist/cjs/common/abstractRefiners.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/abstractRefiners'>;
}
declare module 'chrono-node/dist/cjs/common/calculation/weekdays.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/calculation/weekdays'>;
}
declare module 'chrono-node/dist/cjs/common/casualReferences.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/casualReferences'>;
}
declare module 'chrono-node/dist/cjs/common/parsers/AbstractParserWithWordBoundary.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/parsers/AbstractParserWithWordBoundary'>;
}
declare module 'chrono-node/dist/cjs/common/parsers/AbstractTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/parsers/AbstractTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/common/parsers/ISOFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/parsers/ISOFormatParser'>;
}
declare module 'chrono-node/dist/cjs/common/parsers/SlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/parsers/SlashDateFormatParser'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/AbstractMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/AbstractMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/AbstractMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/AbstractMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/ExtractTimezoneAbbrRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/ExtractTimezoneAbbrRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/ExtractTimezoneOffsetRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/ExtractTimezoneOffsetRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/ForwardDateRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/ForwardDateRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/MergeWeekdayComponentRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/MergeWeekdayComponentRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/OverlapRemovalRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/OverlapRemovalRefiner'>;
}
declare module 'chrono-node/dist/cjs/common/refiners/UnlikelyFormatFilter.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/common/refiners/UnlikelyFormatFilter'>;
}
declare module 'chrono-node/dist/cjs/configurations.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/configurations'>;
}
declare module 'chrono-node/dist/cjs/debugging.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/debugging'>;
}
declare module 'chrono-node/dist/cjs/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs'>;
}
declare module 'chrono-node/dist/cjs/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs'>;
}
declare module 'chrono-node/dist/cjs/locales/de/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/de/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de'>;
}
declare module 'chrono-node/dist/cjs/locales/de/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DECasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DECasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DECasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DECasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DEMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DEMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DESpecificTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DESpecificTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DETimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DETimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DETimeUnitRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DETimeUnitRelativeFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DETimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DETimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/parsers/DEWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/parsers/DEWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/de/refiners/DEMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/refiners/DEMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/de/refiners/DEMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/de/refiners/DEMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/en/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/en/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en'>;
}
declare module 'chrono-node/dist/cjs/locales/en/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENCasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENCasualYearMonthDayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENCasualYearMonthDayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameMiddleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameMiddleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENMonthNameParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENRelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENRelativeDateFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENSlashMonthFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENSlashMonthFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitLaterFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitLaterFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/parsers/ENWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/parsers/ENWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/en/refiners/ENMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/refiners/ENMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/en/refiners/ENMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/refiners/ENMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/en/refiners/ENMergeRelativeDateRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/en/refiners/ENMergeRelativeDateRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/es/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/es/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es'>;
}
declare module 'chrono-node/dist/cjs/locales/es/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es'>;
}
declare module 'chrono-node/dist/cjs/locales/es/parsers/ESCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/parsers/ESCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/es/parsers/ESCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/parsers/ESCasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/es/parsers/ESMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/parsers/ESMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/es/parsers/ESTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/parsers/ESTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/es/parsers/ESTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/parsers/ESTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/es/parsers/ESWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/parsers/ESWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/es/refiners/ESMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/refiners/ESMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/es/refiners/ESMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/es/refiners/ESMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRCasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRSpecificTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRSpecificTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitRelativeFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/parsers/FRWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/parsers/FRWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/refiners/FRMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/refiners/FRMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/fr/refiners/FRMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/fr/refiners/FRMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/ja/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ja/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/ja/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ja'>;
}
declare module 'chrono-node/dist/cjs/locales/ja/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ja'>;
}
declare module 'chrono-node/dist/cjs/locales/ja/parsers/JPCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ja/parsers/JPCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ja/parsers/JPStandardParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ja/parsers/JPStandardParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ja/refiners/JPMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ja/refiners/JPMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualDateTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLCasualDateTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLCasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLCasualYearMonthDayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLCasualYearMonthDayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLMonthNameMiddleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLMonthNameMiddleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLMonthNameParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLRelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLRelativeDateFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLSlashMonthFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLSlashMonthFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitLaterFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitLaterFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/parsers/NLWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/parsers/NLWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/refiners/NLMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/refiners/NLMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/nl/refiners/NLMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/nl/refiners/NLMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/parsers/PTCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/parsers/PTCasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/parsers/PTMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/parsers/PTTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/parsers/PTWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/parsers/PTWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/refiners/PTMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/refiners/PTMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/pt/refiners/PTMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/pt/refiners/PTMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUCasualTimeParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUMonthNameParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RURelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RURelativeDateFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/parsers/RUWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/parsers/RUWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/refiners/RUMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/refiners/RUMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/ru/refiners/RUMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/ru/refiners/RUMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansDeadlineFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansRelationWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansRelationWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/parsers/ZHHansWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/refiners/ZHHansMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/refiners/ZHHansMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hans/refiners/ZHHansMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hans/refiners/ZHHansMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/constants'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantCasualDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantDateParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantDeadlineFormatParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantRelationWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantRelationWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantTimeExpressionParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/parsers/ZHHantWeekdayParser'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/refiners/ZHHantMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/refiners/ZHHantMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/hant/refiners/ZHHantMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh/hant/refiners/ZHHantMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/index' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh'>;
}
declare module 'chrono-node/dist/cjs/locales/zh/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/locales/zh'>;
}
declare module 'chrono-node/dist/cjs/results.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/results'>;
}
declare module 'chrono-node/dist/cjs/timezone.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/timezone'>;
}
declare module 'chrono-node/dist/cjs/utils/dayjs.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/utils/dayjs'>;
}
declare module 'chrono-node/dist/cjs/utils/pattern.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/utils/pattern'>;
}
declare module 'chrono-node/dist/cjs/utils/timeunits.js' {
  declare module.exports: $Exports<'chrono-node/dist/cjs/utils/timeunits'>;
}
declare module 'chrono-node/dist/esm/calculation/mergingCalculation.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/calculation/mergingCalculation'>;
}
declare module 'chrono-node/dist/esm/calculation/years.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/calculation/years'>;
}
declare module 'chrono-node/dist/esm/chrono.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/chrono'>;
}
declare module 'chrono-node/dist/esm/common/abstractRefiners.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/abstractRefiners'>;
}
declare module 'chrono-node/dist/esm/common/calculation/weekdays.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/calculation/weekdays'>;
}
declare module 'chrono-node/dist/esm/common/casualReferences.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/casualReferences'>;
}
declare module 'chrono-node/dist/esm/common/parsers/AbstractParserWithWordBoundary.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/parsers/AbstractParserWithWordBoundary'>;
}
declare module 'chrono-node/dist/esm/common/parsers/AbstractTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/parsers/AbstractTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/common/parsers/ISOFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/parsers/ISOFormatParser'>;
}
declare module 'chrono-node/dist/esm/common/parsers/SlashDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/parsers/SlashDateFormatParser'>;
}
declare module 'chrono-node/dist/esm/common/refiners/AbstractMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/AbstractMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/AbstractMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/AbstractMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/ExtractTimezoneAbbrRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/ExtractTimezoneAbbrRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/ExtractTimezoneOffsetRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/ExtractTimezoneOffsetRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/ForwardDateRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/ForwardDateRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/MergeWeekdayComponentRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/MergeWeekdayComponentRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/OverlapRemovalRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/OverlapRemovalRefiner'>;
}
declare module 'chrono-node/dist/esm/common/refiners/UnlikelyFormatFilter.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/common/refiners/UnlikelyFormatFilter'>;
}
declare module 'chrono-node/dist/esm/configurations.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/configurations'>;
}
declare module 'chrono-node/dist/esm/debugging.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/debugging'>;
}
declare module 'chrono-node/dist/esm/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm'>;
}
declare module 'chrono-node/dist/esm/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm'>;
}
declare module 'chrono-node/dist/esm/locales/de/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/constants'>;
}
declare module 'chrono-node/dist/esm/locales/de/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de'>;
}
declare module 'chrono-node/dist/esm/locales/de/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DECasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DECasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DECasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DECasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DEMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DEMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DESpecificTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DESpecificTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DETimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DETimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DETimeUnitRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DETimeUnitRelativeFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DETimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DETimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/parsers/DEWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/parsers/DEWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/de/refiners/DEMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/refiners/DEMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/de/refiners/DEMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/de/refiners/DEMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/en/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/constants'>;
}
declare module 'chrono-node/dist/esm/locales/en/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en'>;
}
declare module 'chrono-node/dist/esm/locales/en/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENCasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENCasualYearMonthDayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENCasualYearMonthDayParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENMonthNameMiddleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENMonthNameMiddleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENMonthNameParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENRelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENRelativeDateFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENSlashMonthFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENSlashMonthFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitCasualRelativeFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitLaterFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitLaterFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/parsers/ENWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/parsers/ENWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/en/refiners/ENMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/refiners/ENMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/en/refiners/ENMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/refiners/ENMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/en/refiners/ENMergeRelativeDateRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/en/refiners/ENMergeRelativeDateRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/es/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/constants'>;
}
declare module 'chrono-node/dist/esm/locales/es/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es'>;
}
declare module 'chrono-node/dist/esm/locales/es/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es'>;
}
declare module 'chrono-node/dist/esm/locales/es/parsers/ESCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/parsers/ESCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/es/parsers/ESCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/parsers/ESCasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/es/parsers/ESMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/parsers/ESMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/es/parsers/ESTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/parsers/ESTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/es/parsers/ESTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/parsers/ESTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/es/parsers/ESWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/parsers/ESWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/es/refiners/ESMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/refiners/ESMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/es/refiners/ESMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/es/refiners/ESMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/fr/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/constants'>;
}
declare module 'chrono-node/dist/esm/locales/fr/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr'>;
}
declare module 'chrono-node/dist/esm/locales/fr/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRCasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRSpecificTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRSpecificTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitRelativeFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/parsers/FRWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/parsers/FRWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/fr/refiners/FRMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/refiners/FRMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/fr/refiners/FRMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/fr/refiners/FRMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/ja/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ja/constants'>;
}
declare module 'chrono-node/dist/esm/locales/ja/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ja'>;
}
declare module 'chrono-node/dist/esm/locales/ja/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ja'>;
}
declare module 'chrono-node/dist/esm/locales/ja/parsers/JPCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ja/parsers/JPCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/ja/parsers/JPStandardParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ja/parsers/JPStandardParser'>;
}
declare module 'chrono-node/dist/esm/locales/ja/refiners/JPMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ja/refiners/JPMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/nl/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/constants'>;
}
declare module 'chrono-node/dist/esm/locales/nl/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl'>;
}
declare module 'chrono-node/dist/esm/locales/nl/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualDateTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLCasualDateTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLCasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLCasualYearMonthDayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLCasualYearMonthDayParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLMonthNameMiddleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLMonthNameMiddleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLMonthNameParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLRelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLRelativeDateFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLSlashMonthFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLSlashMonthFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitCasualRelativeFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitLaterFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitLaterFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/parsers/NLWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/parsers/NLWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/nl/refiners/NLMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/refiners/NLMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/nl/refiners/NLMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/nl/refiners/NLMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/pt/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/constants'>;
}
declare module 'chrono-node/dist/esm/locales/pt/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt'>;
}
declare module 'chrono-node/dist/esm/locales/pt/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt'>;
}
declare module 'chrono-node/dist/esm/locales/pt/parsers/PTCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/parsers/PTCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/pt/parsers/PTCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/parsers/PTCasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/pt/parsers/PTMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/parsers/PTMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/pt/parsers/PTTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/parsers/PTTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/pt/parsers/PTWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/parsers/PTWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/pt/refiners/PTMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/refiners/PTMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/pt/refiners/PTMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/pt/refiners/PTMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/ru/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/constants'>;
}
declare module 'chrono-node/dist/esm/locales/ru/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru'>;
}
declare module 'chrono-node/dist/esm/locales/ru/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUCasualTimeParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUCasualTimeParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUMonthNameLittleEndianParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUMonthNameLittleEndianParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUMonthNameParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUMonthNameParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RURelativeDateFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RURelativeDateFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitAgoFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitAgoFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitCasualRelativeFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitWithinFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUTimeUnitWithinFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/parsers/RUWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/parsers/RUWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/ru/refiners/RUMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/refiners/RUMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/ru/refiners/RUMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/ru/refiners/RUMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/constants'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansDeadlineFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansRelationWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansRelationWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/parsers/ZHHansWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/refiners/ZHHansMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/refiners/ZHHansMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hans/refiners/ZHHansMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hans/refiners/ZHHansMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/constants.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/constants'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantCasualDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantCasualDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantDateParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantDateParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantDeadlineFormatParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantDeadlineFormatParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantRelationWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantRelationWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantTimeExpressionParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantTimeExpressionParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantWeekdayParser.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/parsers/ZHHantWeekdayParser'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/refiners/ZHHantMergeDateRangeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/refiners/ZHHantMergeDateRangeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/zh/hant/refiners/ZHHantMergeDateTimeRefiner.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh/hant/refiners/ZHHantMergeDateTimeRefiner'>;
}
declare module 'chrono-node/dist/esm/locales/zh/index' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh'>;
}
declare module 'chrono-node/dist/esm/locales/zh/index.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/locales/zh'>;
}
declare module 'chrono-node/dist/esm/results.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/results'>;
}
declare module 'chrono-node/dist/esm/timezone.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/timezone'>;
}
declare module 'chrono-node/dist/esm/utils/dayjs.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/utils/dayjs'>;
}
declare module 'chrono-node/dist/esm/utils/pattern.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/utils/pattern'>;
}
declare module 'chrono-node/dist/esm/utils/timeunits.js' {
  declare module.exports: $Exports<'chrono-node/dist/esm/utils/timeunits'>;
}
