// flow-typed signature: 86dc6f364d86b8f222fe6b5e722ec9ae
// flow-typed version: <<STUB>>/clipboardy_v3.0.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipboardy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipboardy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipboardy/browser' {
  declare module.exports: any;
}

declare module 'clipboardy/lib/linux' {
  declare module.exports: any;
}

declare module 'clipboardy/lib/macos' {
  declare module.exports: any;
}

declare module 'clipboardy/lib/termux' {
  declare module.exports: any;
}

declare module 'clipboardy/lib/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipboardy/browser.js' {
  declare module.exports: $Exports<'clipboardy/browser'>;
}
declare module 'clipboardy/index' {
  declare module.exports: $Exports<'clipboardy'>;
}
declare module 'clipboardy/index.js' {
  declare module.exports: $Exports<'clipboardy'>;
}
declare module 'clipboardy/lib/linux.js' {
  declare module.exports: $Exports<'clipboardy/lib/linux'>;
}
declare module 'clipboardy/lib/macos.js' {
  declare module.exports: $Exports<'clipboardy/lib/macos'>;
}
declare module 'clipboardy/lib/termux.js' {
  declare module.exports: $Exports<'clipboardy/lib/termux'>;
}
declare module 'clipboardy/lib/windows.js' {
  declare module.exports: $Exports<'clipboardy/lib/windows'>;
}
