// flow-typed signature: a8c19498fe640340851a3cf720244161
// flow-typed version: <<STUB>>/eslint-plugin-no-floating-promise_v^1.0.2/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-floating-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-floating-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-floating-promise/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-no-floating-promise/lib/rules/no-floating-promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-floating-promise/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-no-floating-promise/lib'>;
}
declare module 'eslint-plugin-no-floating-promise/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-floating-promise/lib'>;
}
declare module 'eslint-plugin-no-floating-promise/lib/rules/no-floating-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-no-floating-promise/lib/rules/no-floating-promise'>;
}
