// flow-typed signature: dc71b6e52b9764ded63000dd0635c82a
// flow-typed version: <<STUB>>/json5_v^2.2.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json5' {
  declare export default {
    parse: (string) => mixed,
    stringify: (mixed) => string,
  }
}
