// flow-typed signature: 778f3231e4d428ddcfda30672a2f8368
// flow-typed version: <<STUB>>/mermaid_v^10.1.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mermaid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mermaid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mermaid/dist/arc-c50f0902' {
  declare module.exports: any;
}

declare module 'mermaid/dist/arc-f7872e1e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/array-2ff2c7a6' {
  declare module.exports: any;
}

declare module 'mermaid/dist/array-b7dcf730' {
  declare module.exports: any;
}

declare module 'mermaid/dist/c4Diagram-44c43e89' {
  declare module.exports: any;
}

declare module 'mermaid/dist/c4Diagram-be8b5c2c' {
  declare module.exports: any;
}

declare module 'mermaid/dist/c4Diagram-d4b415eb' {
  declare module.exports: any;
}

declare module 'mermaid/dist/classDiagram-634fc78b' {
  declare module.exports: any;
}

declare module 'mermaid/dist/classDiagram-6d218cdd' {
  declare module.exports: any;
}

declare module 'mermaid/dist/classDiagram-7b4b2ee6' {
  declare module.exports: any;
}

declare module 'mermaid/dist/classDiagram-v2-556a8c31' {
  declare module.exports: any;
}

declare module 'mermaid/dist/classDiagram-v2-6aaa1e9f' {
  declare module.exports: any;
}

declare module 'mermaid/dist/classDiagram-v2-72bddc41' {
  declare module.exports: any;
}

declare module 'mermaid/dist/commonDb-41f8b4c5' {
  declare module.exports: any;
}

declare module 'mermaid/dist/commonDb-573409be' {
  declare module.exports: any;
}

declare module 'mermaid/dist/commonDb-89160e91' {
  declare module.exports: any;
}

declare module 'mermaid/dist/constant-2fe7eae5' {
  declare module.exports: any;
}

declare module 'mermaid/dist/constant-b644328d' {
  declare module.exports: any;
}

declare module 'mermaid/dist/createText-1f5f8f92' {
  declare module.exports: any;
}

declare module 'mermaid/dist/createText-23817c58' {
  declare module.exports: any;
}

declare module 'mermaid/dist/createText-b0d5c0ec' {
  declare module.exports: any;
}

declare module 'mermaid/dist/edges-17d4be60' {
  declare module.exports: any;
}

declare module 'mermaid/dist/edges-2e77835f' {
  declare module.exports: any;
}

declare module 'mermaid/dist/edges-de377bae' {
  declare module.exports: any;
}

declare module 'mermaid/dist/erDiagram-20cc9db4' {
  declare module.exports: any;
}

declare module 'mermaid/dist/erDiagram-215b0341' {
  declare module.exports: any;
}

declare module 'mermaid/dist/erDiagram-dfd3761e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowchart-elk-definition-55d9b0bb' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowchart-elk-definition-859d9cf8' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowchart-elk-definition-a44a74cb' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDb-39497bf7' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDb-52e24d17' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDb-bb61b53c' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDiagram-3d69eb42' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDiagram-46a15f6f' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDiagram-7d05970f' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDiagram-v2-6bfe9e0e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDiagram-v2-8e52592d' {
  declare module.exports: any;
}

declare module 'mermaid/dist/flowDiagram-v2-e9772692' {
  declare module.exports: any;
}

declare module 'mermaid/dist/ganttDiagram-04e74c0a' {
  declare module.exports: any;
}

declare module 'mermaid/dist/ganttDiagram-536170c3' {
  declare module.exports: any;
}

declare module 'mermaid/dist/ganttDiagram-6b6599ba' {
  declare module.exports: any;
}

declare module 'mermaid/dist/gitGraphDiagram-0a645df6' {
  declare module.exports: any;
}

declare module 'mermaid/dist/gitGraphDiagram-603d2a33' {
  declare module.exports: any;
}

declare module 'mermaid/dist/gitGraphDiagram-fb502d5b' {
  declare module.exports: any;
}

declare module 'mermaid/dist/index-5219d011' {
  declare module.exports: any;
}

declare module 'mermaid/dist/index-6271e032' {
  declare module.exports: any;
}

declare module 'mermaid/dist/index-c47ff54b' {
  declare module.exports: any;
}

declare module 'mermaid/dist/infoDiagram-24bbb26e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/infoDiagram-388842fb' {
  declare module.exports: any;
}

declare module 'mermaid/dist/infoDiagram-69ec1a58' {
  declare module.exports: any;
}

declare module 'mermaid/dist/init-cc95ec8e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/init-f9637058' {
  declare module.exports: any;
}

declare module 'mermaid/dist/is_dark-a2294536' {
  declare module.exports: any;
}

declare module 'mermaid/dist/is_dark-b77964f3' {
  declare module.exports: any;
}

declare module 'mermaid/dist/journeyDiagram-420adb66' {
  declare module.exports: any;
}

declare module 'mermaid/dist/journeyDiagram-55528350' {
  declare module.exports: any;
}

declare module 'mermaid/dist/journeyDiagram-d38aa57d' {
  declare module.exports: any;
}

declare module 'mermaid/dist/layout-3ff13c4c' {
  declare module.exports: any;
}

declare module 'mermaid/dist/layout-492ec81d' {
  declare module.exports: any;
}

declare module 'mermaid/dist/line-05ccbb85' {
  declare module.exports: any;
}

declare module 'mermaid/dist/line-fbe8f138' {
  declare module.exports: any;
}

declare module 'mermaid/dist/mermaidAPI-3ae0f2f0' {
  declare module.exports: any;
}

declare module 'mermaid/dist/mermaidAPI-67f627de' {
  declare module.exports: any;
}

declare module 'mermaid/dist/mermaidAPI-c841a67f' {
  declare module.exports: any;
}

declare module 'mermaid/dist/mindmap-definition-57c198db' {
  declare module.exports: any;
}

declare module 'mermaid/dist/mindmap-definition-65b51176' {
  declare module.exports: any;
}

declare module 'mermaid/dist/mindmap-definition-b90592f0' {
  declare module.exports: any;
}

declare module 'mermaid/dist/pieDiagram-9555168c' {
  declare module.exports: any;
}

declare module 'mermaid/dist/pieDiagram-db1a8a21' {
  declare module.exports: any;
}

declare module 'mermaid/dist/pieDiagram-ffb7c1e5' {
  declare module.exports: any;
}

declare module 'mermaid/dist/requirementDiagram-51a5ec78' {
  declare module.exports: any;
}

declare module 'mermaid/dist/requirementDiagram-b9649942' {
  declare module.exports: any;
}

declare module 'mermaid/dist/requirementDiagram-ff8da15b' {
  declare module.exports: any;
}

declare module 'mermaid/dist/selectAll-4d781168' {
  declare module.exports: any;
}

declare module 'mermaid/dist/selectAll-7c7a6d44' {
  declare module.exports: any;
}

declare module 'mermaid/dist/sequenceDiagram-3b765acc' {
  declare module.exports: any;
}

declare module 'mermaid/dist/sequenceDiagram-446df3e4' {
  declare module.exports: any;
}

declare module 'mermaid/dist/sequenceDiagram-a52c6980' {
  declare module.exports: any;
}

declare module 'mermaid/dist/stateDiagram-2fc945a0' {
  declare module.exports: any;
}

declare module 'mermaid/dist/stateDiagram-d14e810e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/stateDiagram-d53d2428' {
  declare module.exports: any;
}

declare module 'mermaid/dist/stateDiagram-v2-660a5d6e' {
  declare module.exports: any;
}

declare module 'mermaid/dist/stateDiagram-v2-9765461d' {
  declare module.exports: any;
}

declare module 'mermaid/dist/stateDiagram-v2-c3d22c51' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-123f2a17' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-16907e1b' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-26373982' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-3ce90e7a' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-47a825a5' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-55de9f38' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-a8f89eec' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-b64b35cd' {
  declare module.exports: any;
}

declare module 'mermaid/dist/styles-fd236c01' {
  declare module.exports: any;
}

declare module 'mermaid/dist/svgDraw-0a992cdb' {
  declare module.exports: any;
}

declare module 'mermaid/dist/svgDraw-2526cba0' {
  declare module.exports: any;
}

declare module 'mermaid/dist/svgDraw-dd61ddfa' {
  declare module.exports: any;
}

declare module 'mermaid/dist/timeline-definition-472c301b' {
  declare module.exports: any;
}

declare module 'mermaid/dist/timeline-definition-de69aca6' {
  declare module.exports: any;
}

declare module 'mermaid/dist/timeline-definition-f3a4334c' {
  declare module.exports: any;
}

declare module 'mermaid/dist/utils-1aebe9b6' {
  declare module.exports: any;
}

declare module 'mermaid/dist/utils-8ea37061' {
  declare module.exports: any;
}

declare module 'mermaid/dist/utils-d622194a' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mermaid/dist/arc-c50f0902.js' {
  declare module.exports: $Exports<'mermaid/dist/arc-c50f0902'>;
}
declare module 'mermaid/dist/arc-f7872e1e.js' {
  declare module.exports: $Exports<'mermaid/dist/arc-f7872e1e'>;
}
declare module 'mermaid/dist/array-2ff2c7a6.js' {
  declare module.exports: $Exports<'mermaid/dist/array-2ff2c7a6'>;
}
declare module 'mermaid/dist/array-b7dcf730.js' {
  declare module.exports: $Exports<'mermaid/dist/array-b7dcf730'>;
}
declare module 'mermaid/dist/c4Diagram-44c43e89.js' {
  declare module.exports: $Exports<'mermaid/dist/c4Diagram-44c43e89'>;
}
declare module 'mermaid/dist/c4Diagram-be8b5c2c.js' {
  declare module.exports: $Exports<'mermaid/dist/c4Diagram-be8b5c2c'>;
}
declare module 'mermaid/dist/c4Diagram-d4b415eb.js' {
  declare module.exports: $Exports<'mermaid/dist/c4Diagram-d4b415eb'>;
}
declare module 'mermaid/dist/classDiagram-634fc78b.js' {
  declare module.exports: $Exports<'mermaid/dist/classDiagram-634fc78b'>;
}
declare module 'mermaid/dist/classDiagram-6d218cdd.js' {
  declare module.exports: $Exports<'mermaid/dist/classDiagram-6d218cdd'>;
}
declare module 'mermaid/dist/classDiagram-7b4b2ee6.js' {
  declare module.exports: $Exports<'mermaid/dist/classDiagram-7b4b2ee6'>;
}
declare module 'mermaid/dist/classDiagram-v2-556a8c31.js' {
  declare module.exports: $Exports<'mermaid/dist/classDiagram-v2-556a8c31'>;
}
declare module 'mermaid/dist/classDiagram-v2-6aaa1e9f.js' {
  declare module.exports: $Exports<'mermaid/dist/classDiagram-v2-6aaa1e9f'>;
}
declare module 'mermaid/dist/classDiagram-v2-72bddc41.js' {
  declare module.exports: $Exports<'mermaid/dist/classDiagram-v2-72bddc41'>;
}
declare module 'mermaid/dist/commonDb-41f8b4c5.js' {
  declare module.exports: $Exports<'mermaid/dist/commonDb-41f8b4c5'>;
}
declare module 'mermaid/dist/commonDb-573409be.js' {
  declare module.exports: $Exports<'mermaid/dist/commonDb-573409be'>;
}
declare module 'mermaid/dist/commonDb-89160e91.js' {
  declare module.exports: $Exports<'mermaid/dist/commonDb-89160e91'>;
}
declare module 'mermaid/dist/constant-2fe7eae5.js' {
  declare module.exports: $Exports<'mermaid/dist/constant-2fe7eae5'>;
}
declare module 'mermaid/dist/constant-b644328d.js' {
  declare module.exports: $Exports<'mermaid/dist/constant-b644328d'>;
}
declare module 'mermaid/dist/createText-1f5f8f92.js' {
  declare module.exports: $Exports<'mermaid/dist/createText-1f5f8f92'>;
}
declare module 'mermaid/dist/createText-23817c58.js' {
  declare module.exports: $Exports<'mermaid/dist/createText-23817c58'>;
}
declare module 'mermaid/dist/createText-b0d5c0ec.js' {
  declare module.exports: $Exports<'mermaid/dist/createText-b0d5c0ec'>;
}
declare module 'mermaid/dist/edges-17d4be60.js' {
  declare module.exports: $Exports<'mermaid/dist/edges-17d4be60'>;
}
declare module 'mermaid/dist/edges-2e77835f.js' {
  declare module.exports: $Exports<'mermaid/dist/edges-2e77835f'>;
}
declare module 'mermaid/dist/edges-de377bae.js' {
  declare module.exports: $Exports<'mermaid/dist/edges-de377bae'>;
}
declare module 'mermaid/dist/erDiagram-20cc9db4.js' {
  declare module.exports: $Exports<'mermaid/dist/erDiagram-20cc9db4'>;
}
declare module 'mermaid/dist/erDiagram-215b0341.js' {
  declare module.exports: $Exports<'mermaid/dist/erDiagram-215b0341'>;
}
declare module 'mermaid/dist/erDiagram-dfd3761e.js' {
  declare module.exports: $Exports<'mermaid/dist/erDiagram-dfd3761e'>;
}
declare module 'mermaid/dist/flowchart-elk-definition-55d9b0bb.js' {
  declare module.exports: $Exports<'mermaid/dist/flowchart-elk-definition-55d9b0bb'>;
}
declare module 'mermaid/dist/flowchart-elk-definition-859d9cf8.js' {
  declare module.exports: $Exports<'mermaid/dist/flowchart-elk-definition-859d9cf8'>;
}
declare module 'mermaid/dist/flowchart-elk-definition-a44a74cb.js' {
  declare module.exports: $Exports<'mermaid/dist/flowchart-elk-definition-a44a74cb'>;
}
declare module 'mermaid/dist/flowDb-39497bf7.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDb-39497bf7'>;
}
declare module 'mermaid/dist/flowDb-52e24d17.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDb-52e24d17'>;
}
declare module 'mermaid/dist/flowDb-bb61b53c.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDb-bb61b53c'>;
}
declare module 'mermaid/dist/flowDiagram-3d69eb42.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDiagram-3d69eb42'>;
}
declare module 'mermaid/dist/flowDiagram-46a15f6f.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDiagram-46a15f6f'>;
}
declare module 'mermaid/dist/flowDiagram-7d05970f.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDiagram-7d05970f'>;
}
declare module 'mermaid/dist/flowDiagram-v2-6bfe9e0e.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDiagram-v2-6bfe9e0e'>;
}
declare module 'mermaid/dist/flowDiagram-v2-8e52592d.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDiagram-v2-8e52592d'>;
}
declare module 'mermaid/dist/flowDiagram-v2-e9772692.js' {
  declare module.exports: $Exports<'mermaid/dist/flowDiagram-v2-e9772692'>;
}
declare module 'mermaid/dist/ganttDiagram-04e74c0a.js' {
  declare module.exports: $Exports<'mermaid/dist/ganttDiagram-04e74c0a'>;
}
declare module 'mermaid/dist/ganttDiagram-536170c3.js' {
  declare module.exports: $Exports<'mermaid/dist/ganttDiagram-536170c3'>;
}
declare module 'mermaid/dist/ganttDiagram-6b6599ba.js' {
  declare module.exports: $Exports<'mermaid/dist/ganttDiagram-6b6599ba'>;
}
declare module 'mermaid/dist/gitGraphDiagram-0a645df6.js' {
  declare module.exports: $Exports<'mermaid/dist/gitGraphDiagram-0a645df6'>;
}
declare module 'mermaid/dist/gitGraphDiagram-603d2a33.js' {
  declare module.exports: $Exports<'mermaid/dist/gitGraphDiagram-603d2a33'>;
}
declare module 'mermaid/dist/gitGraphDiagram-fb502d5b.js' {
  declare module.exports: $Exports<'mermaid/dist/gitGraphDiagram-fb502d5b'>;
}
declare module 'mermaid/dist/index-5219d011.js' {
  declare module.exports: $Exports<'mermaid/dist/index-5219d011'>;
}
declare module 'mermaid/dist/index-6271e032.js' {
  declare module.exports: $Exports<'mermaid/dist/index-6271e032'>;
}
declare module 'mermaid/dist/index-c47ff54b.js' {
  declare module.exports: $Exports<'mermaid/dist/index-c47ff54b'>;
}
declare module 'mermaid/dist/infoDiagram-24bbb26e.js' {
  declare module.exports: $Exports<'mermaid/dist/infoDiagram-24bbb26e'>;
}
declare module 'mermaid/dist/infoDiagram-388842fb.js' {
  declare module.exports: $Exports<'mermaid/dist/infoDiagram-388842fb'>;
}
declare module 'mermaid/dist/infoDiagram-69ec1a58.js' {
  declare module.exports: $Exports<'mermaid/dist/infoDiagram-69ec1a58'>;
}
declare module 'mermaid/dist/init-cc95ec8e.js' {
  declare module.exports: $Exports<'mermaid/dist/init-cc95ec8e'>;
}
declare module 'mermaid/dist/init-f9637058.js' {
  declare module.exports: $Exports<'mermaid/dist/init-f9637058'>;
}
declare module 'mermaid/dist/is_dark-a2294536.js' {
  declare module.exports: $Exports<'mermaid/dist/is_dark-a2294536'>;
}
declare module 'mermaid/dist/is_dark-b77964f3.js' {
  declare module.exports: $Exports<'mermaid/dist/is_dark-b77964f3'>;
}
declare module 'mermaid/dist/journeyDiagram-420adb66.js' {
  declare module.exports: $Exports<'mermaid/dist/journeyDiagram-420adb66'>;
}
declare module 'mermaid/dist/journeyDiagram-55528350.js' {
  declare module.exports: $Exports<'mermaid/dist/journeyDiagram-55528350'>;
}
declare module 'mermaid/dist/journeyDiagram-d38aa57d.js' {
  declare module.exports: $Exports<'mermaid/dist/journeyDiagram-d38aa57d'>;
}
declare module 'mermaid/dist/layout-3ff13c4c.js' {
  declare module.exports: $Exports<'mermaid/dist/layout-3ff13c4c'>;
}
declare module 'mermaid/dist/layout-492ec81d.js' {
  declare module.exports: $Exports<'mermaid/dist/layout-492ec81d'>;
}
declare module 'mermaid/dist/line-05ccbb85.js' {
  declare module.exports: $Exports<'mermaid/dist/line-05ccbb85'>;
}
declare module 'mermaid/dist/line-fbe8f138.js' {
  declare module.exports: $Exports<'mermaid/dist/line-fbe8f138'>;
}
declare module 'mermaid/dist/mermaidAPI-3ae0f2f0.js' {
  declare module.exports: $Exports<'mermaid/dist/mermaidAPI-3ae0f2f0'>;
}
declare module 'mermaid/dist/mermaidAPI-67f627de.js' {
  declare module.exports: $Exports<'mermaid/dist/mermaidAPI-67f627de'>;
}
declare module 'mermaid/dist/mermaidAPI-c841a67f.js' {
  declare module.exports: $Exports<'mermaid/dist/mermaidAPI-c841a67f'>;
}
declare module 'mermaid/dist/mindmap-definition-57c198db.js' {
  declare module.exports: $Exports<'mermaid/dist/mindmap-definition-57c198db'>;
}
declare module 'mermaid/dist/mindmap-definition-65b51176.js' {
  declare module.exports: $Exports<'mermaid/dist/mindmap-definition-65b51176'>;
}
declare module 'mermaid/dist/mindmap-definition-b90592f0.js' {
  declare module.exports: $Exports<'mermaid/dist/mindmap-definition-b90592f0'>;
}
declare module 'mermaid/dist/pieDiagram-9555168c.js' {
  declare module.exports: $Exports<'mermaid/dist/pieDiagram-9555168c'>;
}
declare module 'mermaid/dist/pieDiagram-db1a8a21.js' {
  declare module.exports: $Exports<'mermaid/dist/pieDiagram-db1a8a21'>;
}
declare module 'mermaid/dist/pieDiagram-ffb7c1e5.js' {
  declare module.exports: $Exports<'mermaid/dist/pieDiagram-ffb7c1e5'>;
}
declare module 'mermaid/dist/requirementDiagram-51a5ec78.js' {
  declare module.exports: $Exports<'mermaid/dist/requirementDiagram-51a5ec78'>;
}
declare module 'mermaid/dist/requirementDiagram-b9649942.js' {
  declare module.exports: $Exports<'mermaid/dist/requirementDiagram-b9649942'>;
}
declare module 'mermaid/dist/requirementDiagram-ff8da15b.js' {
  declare module.exports: $Exports<'mermaid/dist/requirementDiagram-ff8da15b'>;
}
declare module 'mermaid/dist/selectAll-4d781168.js' {
  declare module.exports: $Exports<'mermaid/dist/selectAll-4d781168'>;
}
declare module 'mermaid/dist/selectAll-7c7a6d44.js' {
  declare module.exports: $Exports<'mermaid/dist/selectAll-7c7a6d44'>;
}
declare module 'mermaid/dist/sequenceDiagram-3b765acc.js' {
  declare module.exports: $Exports<'mermaid/dist/sequenceDiagram-3b765acc'>;
}
declare module 'mermaid/dist/sequenceDiagram-446df3e4.js' {
  declare module.exports: $Exports<'mermaid/dist/sequenceDiagram-446df3e4'>;
}
declare module 'mermaid/dist/sequenceDiagram-a52c6980.js' {
  declare module.exports: $Exports<'mermaid/dist/sequenceDiagram-a52c6980'>;
}
declare module 'mermaid/dist/stateDiagram-2fc945a0.js' {
  declare module.exports: $Exports<'mermaid/dist/stateDiagram-2fc945a0'>;
}
declare module 'mermaid/dist/stateDiagram-d14e810e.js' {
  declare module.exports: $Exports<'mermaid/dist/stateDiagram-d14e810e'>;
}
declare module 'mermaid/dist/stateDiagram-d53d2428.js' {
  declare module.exports: $Exports<'mermaid/dist/stateDiagram-d53d2428'>;
}
declare module 'mermaid/dist/stateDiagram-v2-660a5d6e.js' {
  declare module.exports: $Exports<'mermaid/dist/stateDiagram-v2-660a5d6e'>;
}
declare module 'mermaid/dist/stateDiagram-v2-9765461d.js' {
  declare module.exports: $Exports<'mermaid/dist/stateDiagram-v2-9765461d'>;
}
declare module 'mermaid/dist/stateDiagram-v2-c3d22c51.js' {
  declare module.exports: $Exports<'mermaid/dist/stateDiagram-v2-c3d22c51'>;
}
declare module 'mermaid/dist/styles-123f2a17.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-123f2a17'>;
}
declare module 'mermaid/dist/styles-16907e1b.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-16907e1b'>;
}
declare module 'mermaid/dist/styles-26373982.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-26373982'>;
}
declare module 'mermaid/dist/styles-3ce90e7a.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-3ce90e7a'>;
}
declare module 'mermaid/dist/styles-47a825a5.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-47a825a5'>;
}
declare module 'mermaid/dist/styles-55de9f38.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-55de9f38'>;
}
declare module 'mermaid/dist/styles-a8f89eec.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-a8f89eec'>;
}
declare module 'mermaid/dist/styles-b64b35cd.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-b64b35cd'>;
}
declare module 'mermaid/dist/styles-fd236c01.js' {
  declare module.exports: $Exports<'mermaid/dist/styles-fd236c01'>;
}
declare module 'mermaid/dist/svgDraw-0a992cdb.js' {
  declare module.exports: $Exports<'mermaid/dist/svgDraw-0a992cdb'>;
}
declare module 'mermaid/dist/svgDraw-2526cba0.js' {
  declare module.exports: $Exports<'mermaid/dist/svgDraw-2526cba0'>;
}
declare module 'mermaid/dist/svgDraw-dd61ddfa.js' {
  declare module.exports: $Exports<'mermaid/dist/svgDraw-dd61ddfa'>;
}
declare module 'mermaid/dist/timeline-definition-472c301b.js' {
  declare module.exports: $Exports<'mermaid/dist/timeline-definition-472c301b'>;
}
declare module 'mermaid/dist/timeline-definition-de69aca6.js' {
  declare module.exports: $Exports<'mermaid/dist/timeline-definition-de69aca6'>;
}
declare module 'mermaid/dist/timeline-definition-f3a4334c.js' {
  declare module.exports: $Exports<'mermaid/dist/timeline-definition-f3a4334c'>;
}
declare module 'mermaid/dist/utils-1aebe9b6.js' {
  declare module.exports: $Exports<'mermaid/dist/utils-1aebe9b6'>;
}
declare module 'mermaid/dist/utils-8ea37061.js' {
  declare module.exports: $Exports<'mermaid/dist/utils-8ea37061'>;
}
declare module 'mermaid/dist/utils-d622194a.js' {
  declare module.exports: $Exports<'mermaid/dist/utils-d622194a'>;
}
