// flow-typed signature: 9e67a3865d2f07b10cc7399014d30a36
// flow-typed version: <<STUB>>/react-loader-spinner_v^5.3.4/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loader-spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loader-spinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loader-spinner/dist/esm/helpers' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/BallTriangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Blocks' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/CirclesWithBar' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/ColorRing' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Comment' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Discuss' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Dna' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/FallingLines' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/FidgetSpinner' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/InfinitySpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/LineWave' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/MagnifyingGlass' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/MutatingDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Radio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/RevolvingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/RotatingLines' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/RotatingSquare' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/RotatingTriangles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/TailSpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/ThreeCircles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/ThreeDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Vortex' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/loader/Watch' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/esm/type' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/helpers' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Audio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/BallTriangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Bars' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Blocks' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Circles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/CirclesWithBar' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/ColorRing' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Comment' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Discuss' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Dna' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/FallingLines' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/FidgetSpinner' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Grid' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Hearts' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/InfinitySpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/LineWave' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/MagnifyingGlass' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/MutatingDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Oval' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Puff' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Radio' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/RevolvingDot' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Rings' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/RotatingLines' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/RotatingSquare' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/RotatingTriangles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/TailSpin' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/ThreeCircles' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/ThreeDots' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Triangle' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Vortex' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/loader/Watch' {
  declare module.exports: any;
}

declare module 'react-loader-spinner/dist/type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loader-spinner/dist/esm/helpers.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/helpers'>;
}
declare module 'react-loader-spinner/dist/esm/index' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm'>;
}
declare module 'react-loader-spinner/dist/esm/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Audio'>;
}
declare module 'react-loader-spinner/dist/esm/loader/BallTriangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/BallTriangle'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Bars'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Blocks.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Blocks'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Circles'>;
}
declare module 'react-loader-spinner/dist/esm/loader/CirclesWithBar.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/CirclesWithBar'>;
}
declare module 'react-loader-spinner/dist/esm/loader/ColorRing.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/ColorRing'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Comment.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Comment'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Discuss.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Discuss'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Dna.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Dna'>;
}
declare module 'react-loader-spinner/dist/esm/loader/FallingLines.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/FallingLines'>;
}
declare module 'react-loader-spinner/dist/esm/loader/FidgetSpinner.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/FidgetSpinner'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Grid'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Hearts'>;
}
declare module 'react-loader-spinner/dist/esm/loader/InfinitySpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/InfinitySpin'>;
}
declare module 'react-loader-spinner/dist/esm/loader/LineWave.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/LineWave'>;
}
declare module 'react-loader-spinner/dist/esm/loader/MagnifyingGlass.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/MagnifyingGlass'>;
}
declare module 'react-loader-spinner/dist/esm/loader/MutatingDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/MutatingDots'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Oval'>;
}
declare module 'react-loader-spinner/dist/esm/loader/ProgressBar.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/ProgressBar'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Puff'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Radio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Radio'>;
}
declare module 'react-loader-spinner/dist/esm/loader/RevolvingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/RevolvingDot'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Rings'>;
}
declare module 'react-loader-spinner/dist/esm/loader/RotatingLines.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/RotatingLines'>;
}
declare module 'react-loader-spinner/dist/esm/loader/RotatingSquare.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/RotatingSquare'>;
}
declare module 'react-loader-spinner/dist/esm/loader/RotatingTriangles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/RotatingTriangles'>;
}
declare module 'react-loader-spinner/dist/esm/loader/TailSpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/TailSpin'>;
}
declare module 'react-loader-spinner/dist/esm/loader/ThreeCircles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/ThreeCircles'>;
}
declare module 'react-loader-spinner/dist/esm/loader/ThreeDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/ThreeDots'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Triangle'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Vortex.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Vortex'>;
}
declare module 'react-loader-spinner/dist/esm/loader/Watch.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/loader/Watch'>;
}
declare module 'react-loader-spinner/dist/esm/type.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/esm/type'>;
}
declare module 'react-loader-spinner/dist/helpers.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/helpers'>;
}
declare module 'react-loader-spinner/dist/index' {
  declare module.exports: $Exports<'react-loader-spinner/dist'>;
}
declare module 'react-loader-spinner/dist/index.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist'>;
}
declare module 'react-loader-spinner/dist/loader/Audio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Audio'>;
}
declare module 'react-loader-spinner/dist/loader/BallTriangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/BallTriangle'>;
}
declare module 'react-loader-spinner/dist/loader/Bars.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Bars'>;
}
declare module 'react-loader-spinner/dist/loader/Blocks.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Blocks'>;
}
declare module 'react-loader-spinner/dist/loader/Circles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Circles'>;
}
declare module 'react-loader-spinner/dist/loader/CirclesWithBar.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/CirclesWithBar'>;
}
declare module 'react-loader-spinner/dist/loader/ColorRing.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/ColorRing'>;
}
declare module 'react-loader-spinner/dist/loader/Comment.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Comment'>;
}
declare module 'react-loader-spinner/dist/loader/Discuss.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Discuss'>;
}
declare module 'react-loader-spinner/dist/loader/Dna.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Dna'>;
}
declare module 'react-loader-spinner/dist/loader/FallingLines.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/FallingLines'>;
}
declare module 'react-loader-spinner/dist/loader/FidgetSpinner.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/FidgetSpinner'>;
}
declare module 'react-loader-spinner/dist/loader/Grid.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Grid'>;
}
declare module 'react-loader-spinner/dist/loader/Hearts.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Hearts'>;
}
declare module 'react-loader-spinner/dist/loader/InfinitySpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/InfinitySpin'>;
}
declare module 'react-loader-spinner/dist/loader/LineWave.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/LineWave'>;
}
declare module 'react-loader-spinner/dist/loader/MagnifyingGlass.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/MagnifyingGlass'>;
}
declare module 'react-loader-spinner/dist/loader/MutatingDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/MutatingDots'>;
}
declare module 'react-loader-spinner/dist/loader/Oval.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Oval'>;
}
declare module 'react-loader-spinner/dist/loader/ProgressBar.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/ProgressBar'>;
}
declare module 'react-loader-spinner/dist/loader/Puff.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Puff'>;
}
declare module 'react-loader-spinner/dist/loader/Radio.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Radio'>;
}
declare module 'react-loader-spinner/dist/loader/RevolvingDot.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/RevolvingDot'>;
}
declare module 'react-loader-spinner/dist/loader/Rings.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Rings'>;
}
declare module 'react-loader-spinner/dist/loader/RotatingLines.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/RotatingLines'>;
}
declare module 'react-loader-spinner/dist/loader/RotatingSquare.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/RotatingSquare'>;
}
declare module 'react-loader-spinner/dist/loader/RotatingTriangles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/RotatingTriangles'>;
}
declare module 'react-loader-spinner/dist/loader/TailSpin.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/TailSpin'>;
}
declare module 'react-loader-spinner/dist/loader/ThreeCircles.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/ThreeCircles'>;
}
declare module 'react-loader-spinner/dist/loader/ThreeDots.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/ThreeDots'>;
}
declare module 'react-loader-spinner/dist/loader/Triangle.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Triangle'>;
}
declare module 'react-loader-spinner/dist/loader/Vortex.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Vortex'>;
}
declare module 'react-loader-spinner/dist/loader/Watch.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/loader/Watch'>;
}
declare module 'react-loader-spinner/dist/type.js' {
  declare module.exports: $Exports<'react-loader-spinner/dist/type'>;
}
