// flow-typed signature: 454ebaa69f7aca8dabb8882b98bfba62
// flow-typed version: <<STUB>>/react-select_v^5.7.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select/animated/dist/react-select-animated.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.cjs' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select-animated.esm' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select-async-creatable.esm' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select-async.esm' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select-base.esm' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select-creatable.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-5b950e59.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-78cf371e.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-a86253bb.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-40119e12.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-73d77d2c.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-a4b66b9e.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/useAsync-73d4611a.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/useAsync-c7333178.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useAsync-fd9b28d9.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/useCreatable-10abcf47.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useCreatable-36230047.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/useCreatable-612c7d7e.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/useStateManager-7748b351.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/useStateManager-7e1e8489.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/useStateManager-ce23061c.cjs.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select/animated/dist/react-select-animated.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs.dev'>;
}
declare module 'react-select/animated/dist/react-select-animated.cjs.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs'>;
}
declare module 'react-select/animated/dist/react-select-animated.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.cjs.prod'>;
}
declare module 'react-select/animated/dist/react-select-animated.esm.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select-animated.esm'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs.dev'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.cjs.prod'>;
}
declare module 'react-select/async-creatable/dist/react-select-async-creatable.esm.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select-async-creatable.esm'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs.dev'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs'>;
}
declare module 'react-select/async/dist/react-select-async.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.cjs.prod'>;
}
declare module 'react-select/async/dist/react-select-async.esm.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select-async.esm'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs.dev'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs'>;
}
declare module 'react-select/base/dist/react-select-base.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.cjs.prod'>;
}
declare module 'react-select/base/dist/react-select-base.esm.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select-base.esm'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs.dev'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.cjs.prod'>;
}
declare module 'react-select/creatable/dist/react-select-creatable.esm.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select-creatable.esm'>;
}
declare module 'react-select/dist/index-5b950e59.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/index-5b950e59.cjs.dev'>;
}
declare module 'react-select/dist/index-78cf371e.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/index-78cf371e.cjs.prod'>;
}
declare module 'react-select/dist/index-a86253bb.esm.js' {
  declare module.exports: $Exports<'react-select/dist/index-a86253bb.esm'>;
}
declare module 'react-select/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.dev'>;
}
declare module 'react-select/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs'>;
}
declare module 'react-select/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.prod'>;
}
declare module 'react-select/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.esm'>;
}
declare module 'react-select/dist/Select-40119e12.esm.js' {
  declare module.exports: $Exports<'react-select/dist/Select-40119e12.esm'>;
}
declare module 'react-select/dist/Select-73d77d2c.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/Select-73d77d2c.cjs.dev'>;
}
declare module 'react-select/dist/Select-a4b66b9e.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/Select-a4b66b9e.cjs.prod'>;
}
declare module 'react-select/dist/useAsync-73d4611a.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/useAsync-73d4611a.cjs.prod'>;
}
declare module 'react-select/dist/useAsync-c7333178.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/useAsync-c7333178.cjs.dev'>;
}
declare module 'react-select/dist/useAsync-fd9b28d9.esm.js' {
  declare module.exports: $Exports<'react-select/dist/useAsync-fd9b28d9.esm'>;
}
declare module 'react-select/dist/useCreatable-10abcf47.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/useCreatable-10abcf47.cjs.dev'>;
}
declare module 'react-select/dist/useCreatable-36230047.esm.js' {
  declare module.exports: $Exports<'react-select/dist/useCreatable-36230047.esm'>;
}
declare module 'react-select/dist/useCreatable-612c7d7e.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/useCreatable-612c7d7e.cjs.prod'>;
}
declare module 'react-select/dist/useStateManager-7748b351.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/useStateManager-7748b351.cjs.dev'>;
}
declare module 'react-select/dist/useStateManager-7e1e8489.esm.js' {
  declare module.exports: $Exports<'react-select/dist/useStateManager-7e1e8489.esm'>;
}
declare module 'react-select/dist/useStateManager-ce23061c.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/useStateManager-ce23061c.cjs.prod'>;
}
