// flow-typed signature: 39e24d7551c77b451c633e80a2edd059
// flow-typed version: <<STUB>>/rollup-plugin-visualizer_v^5.9.0/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-visualizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-visualizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-visualizer/dist/bin/cli' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/lib/network' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/lib/sunburst' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/lib/treemap' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/compress' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/data' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/module-mapper' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/render-template' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/sourcemap' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/template-types' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/uid' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/version' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/plugin/warn' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/shared/create-filter' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/shared/create-filter.test' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/dist/shared/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-visualizer/dist/bin/cli.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/bin/cli'>;
}
declare module 'rollup-plugin-visualizer/dist/lib/network.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/lib/network'>;
}
declare module 'rollup-plugin-visualizer/dist/lib/sunburst.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/lib/sunburst'>;
}
declare module 'rollup-plugin-visualizer/dist/lib/treemap.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/lib/treemap'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/compress.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/compress'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/data.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/data'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/index' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/index.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/module-mapper.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/module-mapper'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/render-template.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/render-template'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/sourcemap.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/sourcemap'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/template-types.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/template-types'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/uid.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/uid'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/version.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/version'>;
}
declare module 'rollup-plugin-visualizer/dist/plugin/warn.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/plugin/warn'>;
}
declare module 'rollup-plugin-visualizer/dist/shared/create-filter.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/shared/create-filter'>;
}
declare module 'rollup-plugin-visualizer/dist/shared/create-filter.test.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/shared/create-filter.test'>;
}
declare module 'rollup-plugin-visualizer/dist/shared/types.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/dist/shared/types'>;
}
