// flow-typed signature: 9ab347f57548fa4b59343e970d5bf58f
// flow-typed version: <<STUB>>/@samverschueren/stream-to-observable_v0.3.1/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@samverschueren/stream-to-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@samverschueren/stream-to-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@samverschueren/stream-to-observable/index' {
  declare module.exports: $Exports<'@samverschueren/stream-to-observable'>;
}
declare module '@samverschueren/stream-to-observable/index.js' {
  declare module.exports: $Exports<'@samverschueren/stream-to-observable'>;
}
