// @flow
//--------------------------------------------------------------------------
// Shared data for value-insert choosers and ValueInsertButtons
// (color, icon, pattern, icon-style). Used by ColorChooser, IconChooser,
// PatternChooser, IconStyleChooser and by Forms ValueInsertButtons.
//--------------------------------------------------------------------------

/** Pattern names for bg/row patterns (e.g. lined, squared). */
export const PATTERNS = ['lined', 'squared', 'mini-squared', 'dotted']

/** Font Awesome style names. */
export const ICON_STYLES = ['solid', 'light', 'regular']

/** Curated Font Awesome free icon names (segment after "fa-"). Use as "fa-{style} fa-{name}". */
export const FA_ICON_NAMES = [
  'star',
  'circle',
  'calendar',
  'calendar-day',
  'calendar-alt',
  'clock',
  'check',
  'times',
  'xmark',
  'folder',
  'folder-open',
  'file',
  'file-lines',
  'edit',
  'pen',
  'trash',
  'plus',
  'minus',
  'user',
  'cube',
  'spinner',
  'chevron-down',
  'bell',
  'triangle-exclamation',
  'circle-exclamation',
  'circle-info',
  'circle-question',
  'image',
  'envelope',
  'heart',
  'bookmark',
  'tag',
  'link',
  'copy',
  'filter',
  'search',
  'cog',
  'home',
  'save',
  'upload',
  'download',
  'list',
  'paper-plane',
  'reply',
  'share',
  'lock',
  'unlock',
  'eye',
  'eye-slash',
  'grip-vertical',
  'check-double',
  'square',
  'bolt',
  'fire',
  'flag',
  'gem',
  'globe',
  'key',
  'map-marker',
  'palette',
  'pencil',
  'print',
  'rocket',
  'stamp',
  'certificate',
  'wrench',
  'book',
  'note-sticky',
  'calendar-plus',
  'calendar-check',
  'thumbs-up',
  'thumbs-down',
  'comment',
  'comment-dots',
  'at',
  'hashtag',
  'arrow-right',
  'arrow-left',
  'chart-line',
]
