// flow-typed signature: 26d620f4810a51ef12154e2356530412
// flow-typed version: <<STUB>>/@rollup/plugin-commonjs_v^19.0.0/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-commonjs/dist/index.es' {
  declare module.exports: any;
}

declare module '@rollup/plugin-commonjs/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-commonjs/dist/index.es.js' {
  declare module.exports: $Exports<'@rollup/plugin-commonjs/dist/index.es'>;
}
declare module '@rollup/plugin-commonjs/dist/index' {
  declare module.exports: $Exports<'@rollup/plugin-commonjs/dist'>;
}
declare module '@rollup/plugin-commonjs/dist/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-commonjs/dist'>;
}
