// flow-typed signature: dafbc238c4acfb826e4c15034d618434
// flow-typed version: <<STUB>>/@rollup/plugin-node-resolve_v13.0.4/flow_v0.179.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-node-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-node-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-node-resolve/dist/cjs' {
  declare module.exports: any;
}

declare module '@rollup/plugin-node-resolve/dist/es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-node-resolve/dist/cjs/index' {
  declare module.exports: $Exports<'@rollup/plugin-node-resolve/dist/cjs'>;
}
declare module '@rollup/plugin-node-resolve/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-node-resolve/dist/cjs'>;
}
declare module '@rollup/plugin-node-resolve/dist/es/index' {
  declare module.exports: $Exports<'@rollup/plugin-node-resolve/dist/es'>;
}
declare module '@rollup/plugin-node-resolve/dist/es/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-node-resolve/dist/es'>;
}
