// flow-typed signature: 643b9595eb531ad60956857cd48c6d09
// flow-typed version: <<STUB>>/@rollup/plugin-alias_v^4.0.3/flow_v0.210.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-alias/dist/cjs' {
  declare module.exports: any;
}

declare module '@rollup/plugin-alias/dist/es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-alias/dist/cjs/index' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist/cjs'>;
}
declare module '@rollup/plugin-alias/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist/cjs'>;
}
declare module '@rollup/plugin-alias/dist/es/index' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist/es'>;
}
declare module '@rollup/plugin-alias/dist/es/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist/es'>;
}
